(()=>{
'use strict';
if(!matchMedia('(min-width:901px)').matches||window.__RUS_DESKTOP_V2__)return;window.__RUS_DESKTOP_V2__=true;
const path=(location.pathname.split('/').pop()||'index.html').toLowerCase(),HOME_FIELD_POINTS=3;
const norm=v=>String(v??'').trim().toUpperCase().replace(/\s+/g,' '),num=v=>{if(v===null||v===undefined||String(v).trim()==='')return null;const n=Number(v);return Number.isFinite(n)?n:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const dateVal=v=>{const t=Date.parse(String(v||''));return Number.isFinite(t)?t:0};
const fmtDate=v=>{const t=dateVal(v);return t?new Date(t).toLocaleDateString(undefined,{month:'short',day:'numeric'}):String(v||'TBA')};
const isFinal=g=>num(g?.actualAway)!==null&&num(g?.actualHome)!==null;
function gameHref(g){return`game.html?${new URLSearchParams({date:g?.date||'',away:g?.awayTeam||'',home:g?.homeTeam||''})}`}
function projectedScores(g){const away=num(g?.awayScore),rawHome=num(g?.homeScore);return away===null||rawHome===null?null:{away,home:rawHome+HOME_FIELD_POINTS}}function line(g){const p=projectedScores(g);if(!p)return'RUS Line —';if(p.away===p.home)return'RUS Line PK';const fav=p.away>p.home?g.awayTeam:g.homeTeam,m=Math.abs(p.away-p.home);return`RUS Line ${fav} -${Number.isInteger(m)?m:m.toFixed(1)}`}
function standingsMap(s){const m=new Map();for(const rows of Object.values(s?.byClassification||{}))for(const x of rows||[])m.set(norm(x.team),x);return m}
function rankMap(r){const m=new Map();for(const [cls,arr] of Object.entries(r?.classifications||{}))(arr||[]).forEach((t,i)=>m.set(norm(typeof t==='string'?t:t.team),{rank:i+1,cls}));return m}
function eloChance(a,h){if(a===null||h===null)return null;const hp=1/(1+Math.pow(10,(a-h)/400));return{away:1-hp,home:hp}}
let dataPromise;
async function get(name,fallback){try{const url=`${name}${name.includes('?')?'&':'?'}v=${Date.now()}`;const r=await fetch(url,{cache:'no-store'});return r.ok?await r.json():fallback}catch{return fallback}}
function loadData(){return dataPromise||(dataPromise=Promise.all([
 get('teams-data.json',[]),get('standings-2026.json',{}),get('rankings-current-2026.json',{}),get('elo-summary.json',{}),get('weekly-simulation.json',{})
]).then(([teams,standings,rankings,elo,weekly])=>({teams,teamMap:new Map((teams||[]).map(t=>[norm(t.team),t])),standings:standingsMap(standings),rankings:rankMap(rankings),elo,weekly,games:weekly?.games||[]})))}
function addStyles(){if(document.getElementById('rus-desktop-v2-style'))return;const s=document.createElement('style');s.id='rus-desktop-v2-style';s.textContent=`
@media(min-width:901px){
  body[data-rus-desktop-v2="1"]{background:radial-gradient(circle at 50% -150px,#1b130f 0,#101010 390px,#0d0d0d 900px)!important}
  body[data-rus-desktop-v2="1"]>header{padding:8px 24px!important;background:rgba(4,4,4,.96)!important;border-bottom:3px solid #F14D07!important}
  body[data-rus-desktop-v2="1"]>header .header-content{min-height:66px!important;gap:14px!important}
  body[data-rus-desktop-v2="1"]>header .logo{width:58px!important;height:58px!important;flex:0 0 58px!important}
  body[data-rus-desktop-v2="1"]>header .site-title h1{font-size:25px!important;line-height:1!important;letter-spacing:1.5px!important}
  body[data-rus-desktop-v2="1"]>header .site-title p{font-size:11px!important;margin-top:4px!important}
  body[data-rus-desktop-v2="1"]>nav{background:rgba(7,7,7,.94)!important;backdrop-filter:blur(14px);box-shadow:0 10px 30px rgba(0,0,0,.24)}
  body[data-rus-desktop-v2="1"] .nav-content.rus-nav{flex-wrap:nowrap!important;align-items:stretch!important}
  body[data-rus-desktop-v2="1"] .rus-nav>a,body[data-rus-desktop-v2="1"] .rus-nav details>summary{min-height:46px!important;padding:12px 11px!important;font-size:10px!important;letter-spacing:.25px!important;white-space:nowrap}
  body[data-rus-desktop-v2="1"] .rus-nav .drop{min-width:270px!important;border-radius:0 0 10px 10px!important;overflow:hidden auto!important}
  body[data-rus-desktop-v2="1"] .rus-nav .drop a{display:grid!important;gap:3px!important;padding:10px 13px!important;white-space:normal!important}
  body[data-rus-desktop-v2="1"] .rus-nav .drop a small{display:block;color:#777;font-size:8px;font-weight:700;text-transform:none;letter-spacing:0;line-height:1.25}
  body[data-rus-desktop-v2="1"] .rus-nav .drop a:hover small,body[data-rus-desktop-v2="1"] .rus-nav .drop a.active small{color:#171717}
  .rus-desktop-games-pill{display:flex;align-items:center;gap:7px;min-height:42px;padding:0 11px;border:1px solid #333;border-radius:11px;background:#141414;color:#fff;text-decoration:none;font-size:9px;font-weight:1000;text-transform:uppercase;white-space:nowrap;margin-left:auto}
  .rus-desktop-games-pill .dot{width:8px;height:8px;border-radius:50%;background:#F14D07;box-shadow:0 0 0 4px rgba(241,77,7,.13)}
  .rus-desktop-games-pill strong{color:#F14D07}
  .rus-header-favorites{margin-left:0!important}
  body[data-rus-desktop-v2="1"] main.container,body[data-rus-desktop-v2="1"] .container{width:min(calc(100% - 42px),1500px)!important}
  table.rus-desktop-table{border-collapse:separate!important;border-spacing:0!important}
  table.rus-desktop-table thead th{position:sticky!important;top:0!important;z-index:11!important;box-shadow:0 1px 0 #402016,0 5px 12px rgba(0,0,0,.16)!important}
  table.rus-desktop-table tbody tr:nth-child(even)>td{background:rgba(255,255,255,.018)}
  table.rus-desktop-table tbody tr:hover>td{background:#1b1715!important}
  table.rus-desktop-table td,table.rus-desktop-table th{padding-top:9px!important;padding-bottom:9px!important}
  table.rus-desktop-table .rus-freeze-rank,table.rus-desktop-table .rus-freeze-team{position:sticky!important;z-index:8!important;background:#101010!important}
  table.rus-desktop-table thead .rus-freeze-rank,table.rus-desktop-table thead .rus-freeze-team{z-index:14!important;background:#F14D07!important}
  table.rus-desktop-table .rus-freeze-rank{left:0!important}
  table.rus-desktop-table .rus-freeze-team{left:var(--rus-team-left,0px)!important;box-shadow:7px 0 12px -11px #000}
  .rus-desktop-layout{display:grid!important;grid-template-columns:minmax(0,1fr) 300px!important;gap:22px!important;align-items:start!important}
  .rus-desktop-layout>.back{grid-column:1/-1!important;margin-bottom:-4px!important}
  .rus-desktop-sidebar{position:sticky;top:64px;background:linear-gradient(160deg,#0a0a0a,#151515);border:1px solid #343434;border-top:5px solid var(--rus-side,#F14D07);border-radius:13px;padding:15px;box-shadow:0 18px 40px rgba(0,0,0,.28);max-height:calc(100vh - 85px);overflow:auto}
  .rus-side-head{display:flex;align-items:center;gap:10px;margin-bottom:12px}.rus-side-logo{width:48px;height:48px;object-fit:contain}.rus-side-head h3{font-size:16px;line-height:1.1;text-transform:uppercase}.rus-side-head small{display:block;color:#888;font-size:9px;margin-top:3px}.rus-side-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.rus-side-stat{background:#111;border:1px solid #2d2d2d;border-radius:8px;padding:9px;text-align:center}.rus-side-stat strong{display:block;font-size:17px}.rus-side-stat span{display:block;color:#777;font-size:7px;text-transform:uppercase;font-weight:900;margin-top:3px}.rus-side-game{margin-top:10px;background:#111;border:1px solid #2d2d2d;border-radius:9px;padding:10px}.rus-side-game small{display:block;color:#777;font-size:7px;font-weight:1000;text-transform:uppercase;margin-bottom:5px}.rus-side-game b{display:block;font-size:11px;line-height:1.35}.rus-side-game .line{color:#F14D07;font-size:10px;font-weight:900;margin-top:5px}.rus-side-actions{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:9px}.rus-side-actions a,.rus-side-fav{min-height:35px;display:grid;place-items:center;text-align:center;text-decoration:none;border:1px solid #383838;border-radius:7px;background:#191919;color:#fff;font-size:8px;font-weight:1000;text-transform:uppercase;padding:6px;cursor:pointer}.rus-side-fav.on{color:#F14D07;border-color:#6b2b12;background:#21130e}.rus-side-actions a.primary{background:#F14D07;color:#000;border-color:#F14D07}
  .rus-team-hover{position:fixed;z-index:2147483300;width:280px;pointer-events:none;background:#0c0c0c;border:1px solid #444;border-top:4px solid var(--team,#F14D07);border-radius:11px;padding:12px;box-shadow:0 18px 50px rgba(0,0,0,.55);opacity:0;transform:translateY(4px);transition:opacity .1s ease,transform .1s ease}.rus-team-hover.show{opacity:1;transform:none}.rus-team-hover-head{display:flex;gap:9px;align-items:center}.rus-team-hover-logo{width:38px;height:38px;object-fit:contain}.rus-team-hover h4{font-size:14px;text-transform:uppercase}.rus-team-hover p{color:#888;font-size:9px;line-height:1.45;margin-top:4px}.rus-team-hover-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin-top:9px}.rus-team-hover-stat{background:#151515;border-radius:6px;padding:7px;text-align:center}.rus-team-hover-stat strong{display:block;font-size:13px}.rus-team-hover-stat span{display:block;color:#666;font-size:6px;text-transform:uppercase;font-weight:900;margin-top:2px}.rus-team-hover-next{margin-top:8px;padding-top:8px;border-top:1px solid #282828;color:#bbb;font-size:9px;line-height:1.45}.rus-team-hover-next b{color:#F14D07}
  .rus-home-dash.rus-home-desktopized{display:grid!important;grid-template-columns:minmax(0,1fr) 350px!important;gap:17px!important;padding:20px!important}.rus-home-dash.rus-home-desktopized>.rus-home-dash-head{grid-column:1/-1!important;margin-bottom:0!important}.rus-home-desktop-main,.rus-home-desktop-rail{min-width:0}.rus-home-desktop-main{display:grid;gap:16px}.rus-home-desktop-rail{display:grid;gap:12px;align-content:start}.rus-home-desktopized .rus-home-block{margin-top:0!important}.rus-home-desktopized .rus-home-main-games .rus-home-grid,.rus-home-desktopized .rus-home-main-teams .rus-home-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.rus-home-desktopized .rus-home-row{grid-template-columns:1fr!important;gap:12px!important}.rus-home-desktopized .rus-home-row .rus-home-block{background:#0d0d0d;border:1px solid #292929;border-radius:10px;padding:11px}.rus-home-desktopized .rus-home-continue{background:#0d0d0d;border:1px solid #292929;border-radius:10px;padding:11px}.rus-home-desktopized .rus-home-card,.rus-home-desktopized .rus-home-chip{transition:transform .12s ease,border-color .12s ease}.rus-home-desktopized .rus-home-card:hover,.rus-home-desktopized .rus-home-chip:hover{transform:translateY(-2px);border-color:#5a311f}
}
@media(min-width:901px) and (max-width:1120px){.rus-desktop-layout{grid-template-columns:minmax(0,1fr) 260px!important}.rus-home-dash.rus-home-desktopized{grid-template-columns:minmax(0,1fr) 310px!important}.nav-content.rus-nav{overflow-x:auto!important;scrollbar-width:none}.nav-content.rus-nav::-webkit-scrollbar{display:none}}
`;
document.head.appendChild(s)}
const navDescriptions={
 'championships.html':'State title history and championship games','season.html':'Browse any season in the database','historical-rankings.html':'Past Rural Utah Sports rankings','programs.html':'All-time program leaderboard','streaks.html':'Active and historic streaks','milestones.html':'Programs nearing major milestones','rivalry.html':'Head-to-head rivalry history','dynasty.html':'Explore sustained program dominance','history-lab.html':'Advanced historical research tools','greatest-seasons.html':'Rank the best seasons ever','records.html':'Utah football record book','elo.html':'Power ratings and rating history','playoff-picture.html':'Current RPI and projected seeds','upsets.html':'Biggest ELO upsets','scorigami.html':'Unique final scores','fantasy-football.html':'Fantasy-style player performance','out-of-state.html':'Utah vs. out-of-state history','compare.html':'Compare two programs','player-compare.html':'Compare player production','map.html':'Football schools and geography','stat-leaders.html':'Current individual leaders','weekly-awards.html':'Weekly MVP and class honors','team-stats.html':'Team statistical leaders','mvp-race.html':'Current MVP race','all-utah.html':'RUS All-Utah selections','all-state-watch.html':'All-State and region watch','awards-2025.html':'Past award winners','simulators.html':'Simulation tools','promotion-relegation.html':'Promotion and relegation simulator'
};
function enhanceNav(){document.querySelectorAll('.rus-nav .drop a').forEach(a=>{const file=(a.getAttribute('href')||'').split('?')[0];if(a.querySelector('small')||!navDescriptions[file])return;const sm=document.createElement('small');sm.textContent=navDescriptions[file];a.appendChild(sm)})}
function enhanceTables(){document.querySelectorAll('main table').forEach(table=>{if(table.dataset.rusDesktopV2)return;table.dataset.rusDesktopV2='1';table.classList.add('rus-desktop-table');const heads=[...table.querySelectorAll('thead tr:first-child th')];const teamIndex=heads.findIndex(th=>/^(team|school|program)$/i.test((th.textContent||'').trim()));if(teamIndex<0||teamIndex>1)return;const rows=[...table.rows];if(teamIndex===1){const firstWidth=Math.ceil(rows[0]?.cells?.[0]?.getBoundingClientRect().width||46);rows.forEach(row=>{if(row.cells[0])row.cells[0].classList.add('rus-freeze-rank');if(row.cells[1]){row.cells[1].classList.add('rus-freeze-team');row.cells[1].style.setProperty('--rus-team-left',`${firstWidth}px`)}})}else rows.forEach(row=>row.cells[0]?.classList.add('rus-freeze-team'))})}
async function addGamesPill(){const host=document.querySelector('header .header-content');if(!host||host.querySelector('.rus-desktop-games-pill'))return;const d=await loadData(),now=new Date(),today=d.games.filter(g=>dateVal(g.date)&&new Date(dateVal(g.date)).toDateString()===now.toDateString()),live=today.filter(g=>!isFinal(g));if(!today.length)return;const a=document.createElement('a');a.className='rus-desktop-games-pill';a.href='scoreboard.html';a.innerHTML=`<span class="dot"></span><span><strong>${live.length||today.length}</strong> ${live.length?'Games Today':'Finals Today'}</span>`;const search=host.querySelector('.rus-search-trigger,.rus-header-favorites');search?host.insertBefore(a,search):host.appendChild(a)}
function teamLogo(name){try{return window.RUSSchoolAssets?.logoUrl?.(name)||''}catch{return''}}
function favoriteState(team){try{const a=JSON.parse(localStorage.getItem('rus-favorite-teams-v1')||'[]');return Array.isArray(a)&&a.map(norm).includes(norm(team))}catch{return false}}
function toggleFavorite(team){let a=[];try{a=JSON.parse(localStorage.getItem('rus-favorite-teams-v1')||'[]')}catch{}a=Array.isArray(a)?a:[];const n=norm(team),on=a.map(norm).includes(n);if(on)a=a.filter(x=>norm(x)!==n);else if(a.length<5)a.push(n);else return false;localStorage.setItem('rus-favorite-teams-v1',JSON.stringify([...new Set(a.map(norm))].slice(0,5)));window.dispatchEvent(new CustomEvent('rus-favorites-changed'));return true}
function nextGame(games,team){return games.filter(g=>!isFinal(g)&&(norm(g.awayTeam)===norm(team)||norm(g.homeTeam)===norm(team))).sort((a,b)=>dateVal(a.date)-dateVal(b.date))[0]||null}
function lastGame(games,team){return games.filter(g=>isFinal(g)&&(norm(g.awayTeam)===norm(team)||norm(g.homeTeam)===norm(team))).sort((a,b)=>dateVal(b.date)-dateVal(a.date))[0]||null}
function teamSidebarHTML(team,d){const t=d.teamMap.get(norm(team))||{},s=d.standings.get(norm(team)),r=d.rankings.get(norm(team)),e=num(d.elo?.[norm(team)]?.currentElo),next=nextGame(d.games,team),last=lastGame(d.games,team),isAway=next&&norm(next.awayTeam)===norm(team),opp=next?(isAway?next.homeTeam:next.awayTeam):'',color=/^#[0-9a-f]{3,6}$/i.test(String(t.backgroundColor||''))?t.backgroundColor:'#F14D07',logo=teamLogo(team);let lastText='No final loaded';if(last){const away=norm(last.awayTeam)===norm(team),us=away?num(last.actualAway):num(last.actualHome),them=away?num(last.actualHome):num(last.actualAway),other=away?last.homeTeam:last.awayTeam,res=us===them?'T':us>them?'W':'L';lastText=`${res} ${us}-${them} • ${away?'at':'vs'} ${other}`}
return{color,html:`<div class="rus-side-head">${logo?`<img class="rus-side-logo" src="${esc(logo)}" alt="">`:''}<div><h3>${esc(team)}</h3><small>${esc([t.classification,t.region?`Region ${t.region}`:''].filter(Boolean).join(' • '))}</small></div></div><div class="rus-side-grid"><div class="rus-side-stat"><strong>${s?`${s.wins}-${s.losses}${s.ties?'-'+s.ties:''}`:'—'}</strong><span>2026 Record</span></div><div class="rus-side-stat"><strong>${r?'#'+r.rank:'—'}</strong><span>Class Rank</span></div><div class="rus-side-stat"><strong>${e===null?'—':Math.round(e)}</strong><span>ELO</span></div><div class="rus-side-stat"><strong>${esc(s?.streak||'—')}</strong><span>Streak</span></div></div><div class="rus-side-game"><small>Next Game</small>${next?`<b>${isAway?'at':'vs'} ${esc(opp)} • ${esc(fmtDate(next.date))}</b><div class="line">${esc(line(next))}</div><div class="rus-side-actions"><a class="primary" href="${gameHref(next)}">Game Center</a><a href="scoreboard.html">Scoreboard</a></div>`:'<b>No upcoming game loaded</b>'}</div><div class="rus-side-game"><small>Last Result</small><b>${esc(lastText)}</b></div><button class="rus-side-fav${favoriteState(team)?' on':''}" type="button" data-rus-side-fav="${esc(team)}">${favoriteState(team)?'★ Saved to My Teams':'☆ Add to My Teams'}</button>`}}
async function buildTeamSidebar(){if(path!=='team.html')return;const team=new URLSearchParams(location.search).get('team');if(!team)return;const main=document.querySelector('main.container'),page=document.getElementById('page');if(!main||!page||main.querySelector('.rus-desktop-sidebar'))return;const d=await loadData(),card=teamSidebarHTML(team,d),aside=document.createElement('aside');aside.className='rus-desktop-sidebar';aside.style.setProperty('--rus-side',card.color);aside.innerHTML=card.html;main.classList.add('rus-desktop-layout');main.appendChild(aside);aside.querySelector('[data-rus-side-fav]')?.addEventListener('click',e=>{if(toggleFavorite(team)===false){alert('You can save up to 5 teams.');return}const on=favoriteState(team);e.currentTarget.classList.toggle('on',on);e.currentTarget.textContent=on?'★ Saved to My Teams':'☆ Add to My Teams'})}
async function buildGameSidebar(){if(path!=='game.html')return;const q=new URLSearchParams(location.search),away=q.get('away')||'',home=q.get('home')||'',date=q.get('date')||'';if(!away||!home)return;const main=document.querySelector('main.container'),page=document.getElementById('page');if(!main||!page||main.querySelector('.rus-desktop-sidebar'))return;const d=await loadData(),g=d.games.find(x=>norm(x.awayTeam)===norm(away)&&norm(x.homeTeam)===norm(home)&&(!date||String(x.date||'')===date))||d.games.find(x=>norm(x.awayTeam)===norm(away)&&norm(x.homeTeam)===norm(home));if(!g)return;const ae=num(d.elo?.[norm(away)]?.currentElo),he=num(d.elo?.[norm(home)]?.currentElo),chance=eloChance(ae,he),ar=d.rankings.get(norm(away)),hr=d.rankings.get(norm(home)),as=d.standings.get(norm(away)),hs=d.standings.get(norm(home)),aa=num(g.actualAway),ah=num(g.actualHome),final=aa!==null&&ah!==null,p=projectedScores(g);const aside=document.createElement('aside');aside.className='rus-desktop-sidebar';aside.innerHTML=`<div class="rus-side-head"><div><h3>${esc(away)} at ${esc(home)}</h3><small>${esc(fmtDate(g.date))}</small></div></div><div class="rus-side-game"><small>${final?'Final':'RUS Projected Line'}</small><b>${final?`${aa}-${ah}`:esc(line(g))}</b>${!final?`<div class="line">Projected score ${p?`${esc(p.away)}–${esc(p.home)}`:'—'} • includes home +3</div>`:''}</div><div class="rus-side-grid"><div class="rus-side-stat"><strong>${ar?'#'+ar.rank:'—'}</strong><span>${esc(away)} Rank</span></div><div class="rus-side-stat"><strong>${hr?'#'+hr.rank:'—'}</strong><span>${esc(home)} Rank</span></div><div class="rus-side-stat"><strong>${chance?Math.round(chance.away*100)+'%':'—'}</strong><span>${esc(away)} ELO</span></div><div class="rus-side-stat"><strong>${chance?Math.round(chance.home*100)+'%':'—'}</strong><span>${esc(home)} ELO</span></div></div><div class="rus-side-game"><small>2026 Records</small><b>${esc(away)} ${as?`${as.wins}-${as.losses}${as.ties?'-'+as.ties:''}`:'—'}<br>${esc(home)} ${hs?`${hs.wins}-${hs.losses}${hs.ties?'-'+hs.ties:''}`:'—'}</b></div><div class="rus-side-actions"><a href="team.html?team=${encodeURIComponent(away)}">${esc(away)}</a><a href="team.html?team=${encodeURIComponent(home)}">${esc(home)}</a><a class="primary" href="scoreboard.html">Scoreboard</a><a href="compare.html?team1=${encodeURIComponent(away)}&team2=${encodeURIComponent(home)}">Compare</a></div>`;main.classList.add('rus-desktop-layout');main.appendChild(aside)}
function desktopizeHome(){if(path!=='index.html')return false;const dash=document.querySelector('.rus-home-dash');if(!dash||dash.classList.contains('rus-home-desktopized'))return false;const children=[...dash.children].filter(x=>!x.classList.contains('rus-home-dash-head')),main=document.createElement('div'),rail=document.createElement('aside');main.className='rus-home-desktop-main';rail.className='rus-home-desktop-rail';for(const child of children){const text=(child.querySelector('h3')?.textContent||'').toLowerCase();if(child.classList.contains('rus-home-row'))rail.appendChild(child);else if(/my teams/.test(text)){child.classList.add('rus-home-main-teams');main.appendChild(child)}else if(/games tonight|next games/.test(text)){child.classList.add('rus-home-main-games');main.appendChild(child)}else if(/continue/.test(text)){child.classList.add('rus-home-continue');rail.appendChild(child)}else main.appendChild(child)}dash.append(main,rail);dash.classList.add('rus-home-desktopized');return true}
let hoverTimer,hoverCard;
function hideHover(){clearTimeout(hoverTimer);hoverCard?.classList.remove('show')}
async function showHover(link){const u=new URL(link.href,location.href),team=u.searchParams.get('team');if(!team)return;const d=await loadData();if(!document.body.contains(link))return;const t=d.teamMap.get(norm(team))||{},s=d.standings.get(norm(team)),r=d.rankings.get(norm(team)),e=num(d.elo?.[norm(team)]?.currentElo),next=nextGame(d.games,team),color=/^#[0-9a-f]{3,6}$/i.test(String(t.backgroundColor||''))?t.backgroundColor:'#F14D07',logo=teamLogo(team);if(!hoverCard){hoverCard=document.createElement('div');hoverCard.className='rus-team-hover';document.body.appendChild(hoverCard)}hoverCard.style.setProperty('--team',color);hoverCard.innerHTML=`<div class="rus-team-hover-head">${logo?`<img class="rus-team-hover-logo" src="${esc(logo)}" alt="">`:''}<div><h4>${esc(team)}</h4><p>${esc([t.classification,t.region?`Region ${t.region}`:''].filter(Boolean).join(' • '))}</p></div></div><div class="rus-team-hover-grid"><div class="rus-team-hover-stat"><strong>${s?`${s.wins}-${s.losses}`:'—'}</strong><span>Record</span></div><div class="rus-team-hover-stat"><strong>${r?'#'+r.rank:'—'}</strong><span>Rank</span></div><div class="rus-team-hover-stat"><strong>${e===null?'—':Math.round(e)}</strong><span>ELO</span></div></div>${next?`<div class="rus-team-hover-next"><b>Next:</b> ${esc(next.awayTeam)} at ${esc(next.homeTeam)} • ${esc(fmtDate(next.date))}<br>${esc(line(next))}</div>`:''}`;const rect=link.getBoundingClientRect(),w=280,gap=10;let left=Math.min(window.innerWidth-w-12,Math.max(12,rect.right+gap));if(rect.right+gap+w>window.innerWidth-12)left=Math.max(12,rect.left-w-gap);let top=Math.max(12,Math.min(window.innerHeight-190,rect.top));hoverCard.style.left=`${left}px`;hoverCard.style.top=`${top}px`;requestAnimationFrame(()=>hoverCard.classList.add('show'))}
function bindHover(){document.addEventListener('mouseover',e=>{const a=e.target.closest?.('main a[href*="team.html?team="]');if(!a||a.contains(e.relatedTarget))return;clearTimeout(hoverTimer);hoverTimer=setTimeout(()=>showHover(a),180)});document.addEventListener('mouseout',e=>{const a=e.target.closest?.('main a[href*="team.html?team="]');if(!a||a.contains(e.relatedTarget))return;hideHover()});window.addEventListener('scroll',hideHover,{passive:true});window.addEventListener('resize',hideHover,{passive:true})}
function observe(){const o=new MutationObserver(()=>{enhanceNav();enhanceTables();desktopizeHome()});o.observe(document.body,{childList:true,subtree:true});setTimeout(()=>o.disconnect(),20000)}
function start(){document.body.setAttribute('data-rus-desktop-v2','1');addStyles();enhanceNav();enhanceTables();desktopizeHome();addGamesPill();buildTeamSidebar();buildGameSidebar();bindHover();observe()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
