(() => {
  'use strict';
  const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=v=>Number(v).toFixed(6),signed=v=>`${v>0?'+':''}${fmt(v)}`;
  const states=new WeakMap(),bound=new WeakSet();
  const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th>${h(x)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
  const cell=(...values)=>`<tr>${values.map(v=>`<td>${v}</td>`).join('')}</tr>`;
  const button=(id,label='Load Scenario')=>id?`<button type="button" data-lab-scenario="${h(id)}">${h(label)}</button>`:'—';
  function show(root,data,focus='rooting'){
    states.set(root,data);
    const pill=team=>{const c=data.colors?.[team]||{};return `<span class="rpi-result-team" style="--team-bg:${h(c.background||'#222')};--team-fg:${h(c.text||'#fff')}">${h(team)}</span>`;};
    const details=(name,title,content)=>`<details class="rpi-lab-panel" data-lab-view="${name}"${name===focus?' open':''}><summary>${h(title)}</summary>${content}</details>`;
    const sampleNote=`<p class="rpi-picks-note">Seed swings come from ${data.sampleCount} explored statewide scenarios, not probabilities or exhaustive limits. RPI changes from switching one game’s winner use the fixed final schedule and current out-of-state data.</p>`;
    const rooting=details('rooting',`Who ${data.team} should root for this week`,`${sampleNote}${data.rooting.length?table(['Date','Game','Helpful winner','RPI difference: away win minus home win','Largest seed swing found'],data.rooting.map(g=>cell(h(g.date),`${pill(g.awayTeam)} at ${pill(g.homeTeam)}`,g.conditional?'Depends on other results':g.winner?`${pill(g.winner)}${!g.seedSwing?'<small>Helps RPI; no seed change found</small>':''}`:'No clear preference',signed(g.rpiAwayDelta),h(g.seedSwing)))):'<p>No remaining games with a found effect on this team this week.</p>'}`);
    const impact=details('impact','Games that matter most for the class',`${sampleNote}${table(['Date','Game','Largest total seed movement found','Teams crossing cutoff in one example'],data.impact.map(g=>cell(h(g.date),`${pill(g.awayTeam)} at ${pill(g.homeTeam)}`,h(g.classSwing),h(g.bubbleSwing))))}`);
    const rangeText=x=>x?`${x.highestProven?'Highest possible':'Highest found'}: No. ${x.highest.rank}${x.highest.safeRank!==x.highest.rank?' (tied)':''}; ${x.lowestProven?'lowest possible':'lowest found'}: No. ${x.lowest.rank}${x.lowest.safeRank!==x.lowest.rank?' (tied)':''}`:'—';
    const comparison=details('comparison',`${data.team}: win vs. loss`,data.comparison?`<p>${h(data.comparison.game.date)}: ${pill(data.comparison.game.awayTeam)} at ${pill(data.comparison.game.homeTeam)}</p>${table(['Next-game result','Seed range','Final record in highest example','Example scenarios'],['win','loss'].map(outcome=>{const x=data.comparison[outcome];return cell(outcome==='win'?'Win':'Loss',h(rangeText(x)),h(x.highest.record),`${button(x.highest.scenario,'Highest Scenario')} ${button(x.lowest.scenario,'Lowest Scenario')}`);}))}<p class="rpi-picks-note">Both searches keep the next-game result fixed and explore the other games. “Found” endpoints are not proven limits.</p>`:'<p>No upcoming game is available to compare.</p>');
    const statusRows=rows=>rows.map(r=>cell(h(r.rank??'—'),pill(r.team),h(r.record),h(r.status),`${r.bounds.best}–${r.bounds.worst}`,r.remaining.map(g=>`${h(g.date)}: ${h(g.opponent)}`).join('<br>')||'None'));
    const status=details('status','Clinched and eliminated tracker',`<p>Target: top ${data.cutoff}. Only mathematical bounds produce a clinched or eliminated label. “Unresolved” means this check has not proven either result.</p>${table(['Current seed by calculated RPI','Team','Record','Status','Outer seed bounds','Remaining schedule'],statusRows(data.statuses))}<p class="rpi-picks-note">Proofs apply to the loaded schedule, fixed external opponent data, six-game eligibility and existing exclusions. Official tiebreakers and new schedule changes can affect the final result.</p>`);
    const bubble=data.statuses.filter(r=>r.rank!==null&&(Math.abs(r.rank-data.cutoff)<=4||r.team===data.team));
    const bubbleView=details('bubble',`Playoff bubble: cutoff No. ${data.cutoff}`,`${table(['Current seed by calculated RPI','Team','Record','Status','Outer seed bounds','Remaining schedule'],statusRows(bubble))}<p class="rpi-picks-note">Shows teams within four places of the current cutoff, plus your selected team. Bounds are outer limits; they do not mean every seed in the interval is reachable. The full status tracker lists the entire class.</p>`);
    const minimum=details('minimum',`${data.team}: minimum remaining wins`,`${table(['Remaining record','Result of the search','Best qualifying seed found','Scenario'],data.minimum.map(r=>cell(`${r.wins}–${r.losses}`,h(r.status),r.example?h(r.example.rank):'—',button(r.example?.scenario))))}<p class="rpi-picks-note">A found scenario proves that record can work. A missing scenario is not elimination unless labeled proven. Equal RPI at the cutoff can require an official tiebreaker.</p>`);
    const race=details('race','Head-to-head seed race',data.race?`<p>Can ${pill(data.team)} finish ahead of ${pill(data.race.rival)}?</p><p>${data.race.found?'A verified scenario was found with a higher RPI.':data.race.exhaustive?'No scenario with a strictly higher RPI was found after checking all relevant combinations.':'No scenario found in this search; this does not prove it is impossible.'} Equal RPI is not treated as finishing ahead.</p>${button(data.race.example?.scenario)}`:'<p>No other team is available in this class.</p>');
    const r=data.recap,recap=details('recap','Weekly seed movement recap',`<label>Week of <select data-lab-week>${r.weeks.map(w=>`<option value="${h(w)}"${w===r.week?' selected':''}>${h(w)}</option>`).join('')}</select></label><p>${pill(data.team)}: calculated RPI rank ${h(r.before?.rank??'—')} → ${h(r.after?.rank??'—')}; RPI ${fmt(r.before?.rpi||0)} → ${fmt(r.after?.rpi||0)}.</p>${table(['Date','Result','RPI change when added','Calculated rank before → after'],r.games.map(g=>cell(h(g.date),`${h(g.awayTeam)} ${h(g.away)}–${h(g.home)} ${h(g.homeTeam)}`,signed(g.delta),`${h(g.rankBefore??'—')} → ${h(g.rankAfter??'—')}`)))}<details><summary>Whole-class movement for the week</summary>${table(['Team','Before','After','Movement'],r.movement.map(t=>cell(pill(t.team),h(t.before??'—'),h(t.after),t.change===null?'—':`${t.change>0?'+':''}${t.change}`)))}</details><p class="rpi-picks-note">Calculated from results before and during the selected week, not official week-to-week ranks. Game effects are measured as finals are added in date and team-name order; another order can change the attribution. External opponent records use the current snapshot.</p>`);
    root.innerHTML=`<h3>${h(data.team)} · ${h(data.classification==='8P'?'8-Player':data.classification)} playoff tools</h3><p class="rpi-picks-note">Completed scores stay fixed. Out-of-state data remains at the latest snapshot. All unproven searches are labeled. Use a scenario button to review its full picks in the simulator.</p>${rooting}${impact}${comparison}${status}${minimum}${race}${bubbleView}${recap}`;
    if(!bound.has(root)){bound.add(root);root.addEventListener('click',event=>{
      const b=event.target.closest('[data-lab-scenario]');if(!b)return;
      const d=states.get(root),scenario=d.scenarios[b.dataset.labScenario];if(!scenario)return;
      const picks=Object.fromEntries(d.remaining.map((g,j)=>[window.RUSRpiScenarios.id(g),scenario.bits[j]?g.awayTeam:g.homeTeam]));
      try{localStorage.setItem('rus-rpi-picks-2026-v1',JSON.stringify(picks));}catch{return;}
      window.dispatchEvent(new CustomEvent('rus-rpi-scenario',{detail:picks}));
      if(document.getElementById('rpiPicksBody').hidden)document.getElementById('rpiPicksOpen').click();
      document.getElementById('rpiPicks').scrollIntoView({behavior:'smooth',block:'start'});
    });root.addEventListener('change',event=>{if(event.target.matches('[data-lab-week]'))window.dispatchEvent(new CustomEvent('rus-rpi-lab-week',{detail:{team:states.get(root).team,week:event.target.value}}));});}
  }
  window.RUSRpiLab={show};
  const form=document.getElementById('rpiLabForm');if(!form)return;
  const teamSelect=document.getElementById('rpiLabTeam'),rivalSelect=document.getElementById('rpiLabRival'),classificationSelect=document.getElementById('rpiLabClass'),status=document.getElementById('rpiLabStatus'),output=document.getElementById('rpiLabResult'),submit=form.querySelector('[type=submit]'),cancel=document.getElementById('rpiLabCancel');
  let data,worker,loading=false,week;
  const get=async file=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(`${file}?v=${Date.now()}`,{cache:'no-store',signal:controller.signal});if(!r.ok)throw new Error('Could not load the current schedule. Try again.');return await r.json();}finally{clearTimeout(timer);}};
  async function load(){if(data)return data;const [teams,weekly,oos]=await Promise.all([get('teams-data.json'),get('weekly-simulation.json'),get('rpi-oos-2026.json')]);const unique=new Map();weekly.games.filter(g=>g.awayTeam&&g.homeTeam&&new Date(g.date).getFullYear()===2026).forEach(g=>{const id=window.RUSRpiScenarios.id(g),prior=unique.get(id);if(!prior||window.RUSRpiPaths.final(g))unique.set(id,g);});data={teams,games:[...unique.values()].sort((a,b)=>new Date(a.date)-new Date(b.date)||a.awayTeam.localeCompare(b.awayTeam)),oos};return data;}
  function rivals(){const current=teamSelect.value;rivalSelect.innerHTML=[...teamSelect.options].filter(o=>o.value!==current).map(o=>`<option value="${h(o.value)}">${h(o.value)}</option>`).join('');}
  function teamOptions(){teamSelect.innerHTML=data.teams.filter(t=>!['GRAND','LAYTONCHRISTIAN'].includes(key(t.team))&&(key(t.team)==='ENTERPRISE'?'1A':t.classification)===classificationSelect.value).sort((a,b)=>a.team.localeCompare(b.team)).map(t=>`<option>${h(t.team)}</option>`).join('');rivals();}
  const key=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
  function idle(){loading=false;submit.disabled=false;cancel.hidden=true;form.setAttribute('aria-busy','false');}
  async function run(){if(loading)return;loading=true;submit.disabled=true;cancel.hidden=false;form.setAttribute('aria-busy','true');status.textContent='Loading playoff tools…';try{await load();if(!loading)return;if(!teamSelect.options.length)teamOptions();const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Denver',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),part=t=>parts.find(p=>p.type===t).value;
    const request={team:teamSelect.value,classification:classificationSelect.value,mode:'lab',raceTeam:rivalSelect.value,week,asOf:`${part('year')}-${part('month')}-${part('day')}`};
    if(!worker){worker=new Worker(new URL('rpi-paths-worker.js?v=20261001-lab5',document.baseURI));worker.onmessage=event=>{const m=event.data;if(m.type==='progress')status.textContent=`Preparing RPI: ${m.done}/${m.total} games…`;else if(m.type==='stage')status.textContent=m.message;else if(m.type==='result'){idle();status.textContent='Analysis complete.';show(output,m.result.lab);}else if(m.type==='error'){idle();status.textContent=m.message;}};worker.onerror=()=>{idle();status.textContent='The analysis could not finish. Please try again.';worker.terminate();worker=null;};}
    worker.postMessage({...data,request});
  }catch(error){idle();status.textContent=error.message;}}
  // Populate selectors on focus; analysis starts only after an explicit action.
  form.addEventListener('focusin',async()=>{if(!data)try{await load();teamOptions();}catch(error){status.textContent=error.message;}},{once:true});
  classificationSelect.addEventListener('change',async()=>{try{await load();teamOptions();week=null;}catch(error){status.textContent=error.message;}});teamSelect.addEventListener('change',rivals);
  form.addEventListener('submit',event=>{event.preventDefault();run();});
  cancel.addEventListener('click',()=>{if(worker)worker.terminate();worker=null;idle();status.textContent='Analysis cancelled.';});
  window.addEventListener('rus-rpi-lab-week',async event=>{if(loading)return;await load();const team=data.teams.find(t=>t.team===event.detail.team);if(team){classificationSelect.value=key(team.team)==='ENTERPRISE'?'1A':team.classification;teamOptions();teamSelect.value=team.team;rivals();week=event.detail.week;run();}});
})();
