(()=>{
  const ORANGE='#F14D07';
  const norm=v=>String(v??'').trim().toUpperCase();
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
  const path=(location.pathname.split('/').pop()||'index.html').toLowerCase();
  let teamPromise=null,champPromise=null,gamePromise=null,streakPromise=null;
  const json=(url)=>fetch(`${url}${url.includes('?')?'&':'?'}v=${Date.now()}`).then(r=>{if(!r.ok)throw new Error(url);return r.json()});
  const teams=()=>teamPromise||(teamPromise=json('teams-data.json'));
  const champs=()=>champPromise||(champPromise=json('championships.json'));
  const streaks=()=>streakPromise||(streakPromise=json('streak-records.json'));
  const canonicalTeam=v=>{const name=String(v??'').trim(),n=norm(name).replace(/\.+$/,'').trim();return n.startsWith('WASATCH ACAD')?'WASATCH ACADEMY':name};
  const yearOf=d=>{const m=String(d||'').match(/(?:^|\D)(18\d{2}|19\d{2}|20\d{2})(?:\D|$)/);return m?Number(m[1]):null};
  const dateValue=d=>{const t=Date.parse(String(d||''));return Number.isFinite(t)?t:(yearOf(d)?Date.UTC(yearOf(d),0,1):0)};
  function flattenScorigami(data){
    const out=[],seen=new Set();
    for(const entry of (data.scores||[])) for(const g of (Array.isArray(entry.games)?entry.games:[])){
      let row;
      if(g.tie){row={date:g.date||'',team1:canonicalTeam(g.team1),team2:canonicalTeam(g.team2),score1:Number(g.score1),score2:Number(g.score2),tie:true};}
      else{row={date:g.date||'',team1:canonicalTeam(g.winner),team2:canonicalTeam(g.loser),score1:Number(g.winnerScore),score2:Number(g.loserScore),tie:false};}
      row.year=yearOf(row.date);row.total=row.score1+row.score2;row.margin=Math.abs(row.score1-row.score2);
      const pairs=[[norm(row.team1).replace(/[^A-Z0-9]/g,''),row.score1],[norm(row.team2).replace(/[^A-Z0-9]/g,''),row.score2]].sort((a,b)=>a[0].localeCompare(b[0]));
      const k=`${row.date}|${pairs[0][0]}:${pairs[0][1]}|${pairs[1][0]}:${pairs[1][1]}`;
      if(!seen.has(k)){seen.add(k);out.push(row)}
    }
    return out;
  }
  const games=()=>gamePromise||(gamePromise=json('scorigami.json').then(flattenScorigami));
  function gameURL(g){const q=new URLSearchParams({date:g.date||'',team1:g.team1||'',score1:String(g.score1??''),team2:g.team2||'',score2:String(g.score2??'')});return `game.html?${q}`}

  function ensureStyles(){
    if(document.getElementById('rus-site-extras-style'))return;
    const s=document.createElement('style');s.id='rus-site-extras-style';s.textContent=`
      .rus-search-trigger{margin-left:auto;background:#171717!important;border:0;border-left:1px solid #333;color:#fff!important;cursor:pointer;font:inherit;padding:15px 16px;font-size:13px;font-weight:900;text-transform:uppercase}.rus-search-trigger:hover{background:${ORANGE}!important;color:#000!important}
      .rus-search-overlay{position:fixed;inset:0;background:rgba(0,0,0,.82);z-index:9999;display:none;padding:8vh 16px}.rus-search-overlay.open{display:block}.rus-search-modal{max-width:760px;margin:auto;background:#101010;border:1px solid #444;border-top:5px solid ${ORANGE};border-radius:9px;box-shadow:0 24px 70px rgba(0,0,0,.65);overflow:hidden}.rus-search-head{display:flex;align-items:center;border-bottom:1px solid #333}.rus-search-input{flex:1;background:#101010;color:#fff;border:0;padding:19px 18px;font-size:20px;outline:0}.rus-search-close{background:transparent;color:#aaa;border:0;padding:18px;font-size:22px;cursor:pointer}.rus-search-results{max-height:60vh;overflow:auto;padding:8px}.rus-search-item{display:block;color:#fff;text-decoration:none;padding:13px 14px;border-radius:6px;border:1px solid transparent}.rus-search-item:hover,.rus-search-item.active{background:#1d1d1d;border-color:#444}.rus-search-item strong{display:block}.rus-search-item span{display:block;color:#888;font-size:11px;margin-top:4px;text-transform:uppercase}.rus-search-empty{padding:30px;color:#888;text-align:center}.rus-search-hint{padding:11px 15px;color:#666;border-top:1px solid #292929;font-size:11px}
      .rus-home-search{margin-top:26px;max-width:760px;position:relative}.rus-home-search label{display:block;color:${ORANGE};font-size:12px;font-weight:900;text-transform:uppercase;margin-bottom:8px}.rus-home-search-row{display:flex;gap:8px}.rus-home-search input{flex:1;min-width:0;background:#171717;color:#fff;border:1px solid #444;border-radius:6px;padding:14px 15px;font-size:16px}.rus-home-search button,.rus-random-btn{background:${ORANGE};color:#000;border:0;border-radius:6px;padding:0 18px;font-weight:900;text-transform:uppercase;cursor:pointer}.rus-home-search button:hover,.rus-random-btn:hover{background:#fff}.rus-home-search-links{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.rus-home-search-links a{color:#aaa;font-size:11px;text-decoration:none}.rus-home-search-links a:hover{color:#fff}
      .rus-feature-section{background:#000;border:1px solid #333;border-top:4px solid ${ORANGE};border-radius:8px;padding:22px;margin:24px 0}.rus-feature-head{display:flex;justify-content:space-between;align-items:flex-end;gap:14px;flex-wrap:wrap;margin-bottom:14px}.rus-feature-head h2{font-size:24px;text-transform:uppercase}.rus-feature-head p{color:#888;margin-top:5px;font-size:12px;line-height:1.45}.rus-history-grid,.rus-watch-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.rus-history-card,.rus-watch-card{display:block;background:#171717;border:1px solid #333;border-radius:7px;padding:14px;color:#fff;text-decoration:none}.rus-history-card:hover,.rus-watch-card:hover{border-color:${ORANGE}}.rus-history-card strong,.rus-watch-card strong{display:block;color:${ORANGE};font-size:16px}.rus-history-card span,.rus-watch-card span{display:block;color:#aaa;font-size:12px;line-height:1.45;margin-top:5px}.rus-feature-loading{color:#888;padding:18px 0}.rus-record-distance{color:#777!important;font-size:10px!important;text-transform:uppercase}.rus-random-btn{padding:10px 14px}
      .rus-related{margin:34px 0 5px;background:#000;border:1px solid #333;border-radius:8px;padding:20px}.rus-related h2{text-transform:uppercase;font-size:20px;border-left:5px solid ${ORANGE};padding-left:11px;margin-bottom:13px}.rus-related-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.rus-related a{background:#171717;border:1px solid #333;color:#fff;text-decoration:none;border-radius:6px;padding:13px;font-weight:800;font-size:12px}.rus-related a:hover{border-color:${ORANGE}}.rus-related a span{display:block;color:#777;font-size:9px;text-transform:uppercase;margin-top:4px}
      .rus-game-detail-link{color:${ORANGE};font-weight:900;text-decoration:none}.rus-game-detail-link:hover{text-decoration:underline}.rus-extra-card{position:relative}
      @media(max-width:850px){.rus-history-grid,.rus-watch-grid,.rus-related-grid{grid-template-columns:repeat(2,1fr)}}
      @media(max-width:700px){.rus-search-trigger{margin-left:0}.rus-search-overlay{padding-top:4vh}.rus-home-search-row{flex-direction:column}.rus-home-search button{min-height:44px}.rus-history-grid,.rus-watch-grid,.rus-related-grid{grid-template-columns:1fr}}
    `;document.head.appendChild(s);
  }

  function setupSearch(){
    const nav=document.querySelector('.nav-content.rus-nav')||document.querySelector('nav .nav-content');
    if(nav&&!document.getElementById('rusSearchTrigger')){const b=document.createElement('button');b.id='rusSearchTrigger';b.className='rus-search-trigger';b.type='button';b.textContent='Search ⌕';b.setAttribute('aria-label','Search Rural Utah Sports');nav.appendChild(b)}
    if(!document.getElementById('rusSearchOverlay'))document.body.insertAdjacentHTML('beforeend',`<div class="rus-search-overlay" id="rusSearchOverlay" aria-hidden="true"><div class="rus-search-modal" role="dialog" aria-modal="true" aria-label="Site search"><div class="rus-search-head"><input class="rus-search-input" id="rusSearchInput" type="search" placeholder="Search teams, seasons, games, championships…" autocomplete="off"><button class="rus-search-close" id="rusSearchClose" aria-label="Close">×</button></div><div class="rus-search-results" id="rusSearchResults"><div class="rus-search-empty">Start typing to explore Rural Utah Sports.</div></div><div class="rus-search-hint">Tip: try “Morgan”, “2009”, or “Kanab vs Beaver”. Keyboard shortcut: Ctrl/Cmd + K.</div></div></div>`);
    const overlay=document.getElementById('rusSearchOverlay'),input=document.getElementById('rusSearchInput'),results=document.getElementById('rusSearchResults');
    const open=(preset='')=>{overlay.classList.add('open');overlay.setAttribute('aria-hidden','false');input.value=preset;setTimeout(()=>input.focus(),0);runSearch(preset,results)};const close=()=>{overlay.classList.remove('open');overlay.setAttribute('aria-hidden','true')};
    document.getElementById('rusSearchTrigger')?.addEventListener('click',()=>open());document.getElementById('rusSearchClose')?.addEventListener('click',close);overlay.addEventListener('click',e=>{if(e.target===overlay)close()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open()}if(e.key==='Escape'&&overlay.classList.contains('open'))close()});let timer;input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>runSearch(input.value,results),70)});window.RUSOpenSearch=open;
  }

  const corePages=[['Games Database','games.html','Search every recorded game'],['Season Explorer','season.html','Open any year in Utah football history'],['Program Leaderboard','programs.html','Compare programs across eras'],['Championships','championships.html','Champions and playoff brackets'],['Greatest Seasons','greatest-seasons.html','Top individual team seasons'],['Records','records.html','All-time records and streaks'],['ELO','elo.html','Historical team strength'],['Scorigami','scorigami.html','Unique football scores'],['Team Comparison','compare.html','Compare two programs'],['Rankings','rankings.html','Current RUS rankings'],['Standings','standings.html','Current region and classification standings'],['Simulators','simulators.html','Matchup and weekly simulators']];
  async function runSearch(raw,host){
    const q=String(raw||'').trim();if(!q){host.innerHTML='<div class="rus-search-empty">Start typing to explore Rural Utah Sports.</div>';return}const u=norm(q),items=[];for(const [label,href,desc] of corePages)if(norm(label+' '+desc).includes(u))items.push({label,href,desc,type:'Section'});
    if(/^\d{4}$/.test(q)&&Number(q)>=1800&&Number(q)<=2100)items.unshift({label:`${q} Season`,href:`season.html?year=${q}`,desc:'Games, champions, records and notable results',type:'Season'});
    const matchup=q.split(/\s+(?:vs\.?|v\.?|@)\s+/i);if(matchup.length===2){items.unshift({label:`${matchup[0]} vs ${matchup[1]}`,href:`games.html?search=${encodeURIComponent(matchup[0]+' vs '+matchup[1])}`,desc:'View all meetings in the game database',type:'Matchup'});items.push({label:'Compare these programs',href:`compare.html?team1=${encodeURIComponent(matchup[0].trim().toUpperCase())}&team2=${encodeURIComponent(matchup[1].trim().toUpperCase())}`,desc:'Side-by-side program history',type:'Comparison'})}
    try{const data=await teams();for(const t of data.filter(t=>norm(`${t.team} ${t.mascot||''} ${t.classification||''} ${t.region||''}`).includes(u)).slice(0,8))items.push({label:t.team,href:`team.html?team=${encodeURIComponent(t.team)}`,desc:`${t.classification||'—'} • ${t.region||'—'} • ${Number(t.wins||0).toLocaleString()} wins`,type:'Team'})}catch(e){}
    try{const data=await champs(),matches=data.filter(c=>norm(`${c.year} ${c.classification} ${c.champion} ${c.runnerUp}`).includes(u)&&c.champion).slice(-6).reverse();for(const c of matches)items.push({label:`${c.year} ${c.classification} — ${c.champion}`,href:`championships.html?year=${c.year}&class=${encodeURIComponent(c.classification)}`,desc:c.score?`${c.champion} ${c.score} ${c.runnerUp}`:'Championship history',type:'Championship'})}catch(e){}
    items.push({label:`Search games for “${q}”`,href:`games.html?search=${encodeURIComponent(q)}`,desc:'Search the full game database',type:'Games'});const unique=[],seen=new Set();for(const x of items){if(seen.has(x.href))continue;seen.add(x.href);unique.push(x);if(unique.length>=14)break}host.innerHTML=unique.length?unique.map(x=>`<a class="rus-search-item" href="${x.href}"><strong>${esc(x.label)}</strong><span>${esc(x.type)} • ${esc(x.desc)}</span></a>`).join(''):'<div class="rus-search-empty">No matches found.</div>';
  }

  function setupHomeSearch(){if(path!=='index.html')return;const hero=document.querySelector('.hero');if(!hero||hero.querySelector('.rus-home-search'))return;hero.insertAdjacentHTML('beforeend',`<div class="rus-home-search"><label for="rusHomeSearch">What do you want to find?</label><div class="rus-home-search-row"><input id="rusHomeSearch" type="search" placeholder="Team, season, matchup, championship…"><button id="rusHomeSearchGo">Search</button></div><div class="rus-home-search-links"><a href="season.html">Browse seasons</a><a href="programs.html">Program leaderboard</a><a href="games.html">Game database</a><a href="#" id="rusRandomHistory">Random history</a></div></div>`);const input=document.getElementById('rusHomeSearch'),go=()=>window.RUSOpenSearch?.(input.value);document.getElementById('rusHomeSearchGo').onclick=go;input.addEventListener('keydown',e=>{if(e.key==='Enter')go()});document.getElementById('rusRandomHistory').addEventListener('click',e=>{e.preventDefault();randomHistory()})}
  async function randomHistory(){try{const [ts,cs]=await Promise.all([teams(),champs()]),choices=[];for(const t of ts)choices.push(`team.html?team=${encodeURIComponent(t.team)}`);for(const c of cs.filter(c=>c.champion))choices.push(`championships.html?year=${c.year}&class=${encodeURIComponent(c.classification)}`);for(const y of [...new Set(cs.map(c=>c.year).filter(Boolean))])choices.push(`season.html?year=${y}`);location.href=choices[Math.floor(Math.random()*choices.length)]||'teams.html'}catch(e){location.href='teams.html'}}
  function setupHomeCards(){if(path!=='index.html')return;const cards=document.querySelector('.cards');if(!cards||cards.querySelector('.rus-extra-card'))return;cards.insertAdjacentHTML('beforeend',`<div class="card rus-extra-card"><h3>Season Explorer</h3><p>Open any season as a digital yearbook with champions, records, notable games, and the full schedule.</p><a href="season.html">Explore Seasons</a></div><div class="card rus-extra-card"><h3>Program Leaderboard</h3><p>Rank Utah programs by wins, win percentage, titles, winning seasons, scoring margin, and peak ELO across different eras.</p><a href="programs.html">View Programs</a></div>`)}

  function setupHomeHistory(){if(path!=='index.html')return;const week=document.querySelector('.this-week');if(!week||document.getElementById('rusOnThisDay'))return;week.insertAdjacentHTML('afterend',`<section class="rus-feature-section" id="rusOnThisDay"><div class="rus-feature-head"><div><h2>Today in Utah Football History</h2><p id="rusHistoryDate">Games recorded on this calendar date across Utah high school football history.</p></div><button class="rus-random-btn" id="rusRandomBtn">Random History</button></div><div id="rusHistoryBody" class="rus-feature-loading">History will load when this section comes into view.</div></section><section class="rus-feature-section" id="rusRecordWatch"><div class="rus-feature-head"><div><h2>Record Watch — Latest Recorded Streaks</h2><p>Based on the newest results currently in the RUS game database.</p></div><a href="records.html" style="color:${ORANGE};font-weight:900;text-decoration:none">View Records →</a></div><div id="rusWatchBody" class="rus-feature-loading">Streak watch will load with historical results.</div></section>`);document.getElementById('rusRandomBtn').onclick=randomHistory;const target=document.getElementById('rusOnThisDay');let started=false;const load=()=>{if(started)return;started=true;loadHomeHistory()};if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>{if(es.some(e=>e.isIntersecting)){io.disconnect();load()}},{rootMargin:'350px'});io.observe(target)}else load()}
  async function loadHomeHistory(){const h=document.getElementById('rusHistoryBody'),w=document.getElementById('rusWatchBody');try{const [gs,sr]=await Promise.all([games(),streaks()]);const now=new Date(),month=now.getMonth()+1,day=now.getDate();document.getElementById('rusHistoryDate').textContent=`Games recorded on ${now.toLocaleString(undefined,{month:'long'})} ${day} across Utah football history.`;const exact=gs.filter(g=>{const m=String(g.date).match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);return m&&Number(m[1])===month&&Number(m[2])===day}).sort((a,b)=>b.total-a.total||b.year-a.year).slice(0,6);h.innerHTML=exact.length?`<div class="rus-history-grid">${exact.map(g=>`<a class="rus-history-card" href="${gameURL(g)}"><strong>${esc(g.team1)} ${g.score1}–${g.score2} ${esc(g.team2)}</strong><span>${esc(g.date)} • ${g.total} total points</span></a>`).join('')}</div>`:`<div class="rus-feature-loading">No exact-date games are recorded for today yet. <a href="season.html" style="color:${ORANGE}">Explore a season instead.</a></div>`;const byTeam=new Map();for(const g of [...gs].sort((a,b)=>dateValue(a.date)-dateValue(b.date))){for(const [team,isFirst] of [[g.team1,true],[g.team2,false]]){const k=norm(team),prev=byTeam.get(k)||{team,active:0,last:0};if(g.tie)prev.active=0;else if(isFirst)prev.active+=1;else prev.active=0;prev.last=dateValue(g.date);byTeam.set(k,prev)}}const watch=[...byTeam.entries()].map(([k,v])=>{const best=Number(sr?.[k]?.longestWinStreak?.length||0);return{...v,best,distance:best-v.active}}).filter(x=>x.active>=2).sort((a,b)=>(Math.max(a.distance,0)-Math.max(b.distance,0))||b.active-a.active||b.last-a.last).slice(0,6);w.innerHTML=watch.length?`<div class="rus-watch-grid">${watch.map(x=>`<a class="rus-watch-card" href="team.html?team=${encodeURIComponent(x.team)}"><strong>${esc(x.team)} — ${x.active} straight wins</strong><span>Program record: ${x.best||'—'} wins</span><span class="rus-record-distance">${x.best?x.distance<=0?'At or beyond listed program record':`${x.distance} win${x.distance===1?'':'s'} from record`:'Program record unavailable'}</span></a>`).join('')}</div>`:'<div class="rus-feature-loading">No multi-game active win streaks are available in the latest recorded results.</div>'}catch(e){console.error(e);if(h)h.textContent='Historical games could not be loaded.';if(w)w.textContent='Streak data could not be loaded.'}}

  function setupRelated(){const main=document.querySelector('main');if(!main||main.querySelector('.rus-related'))return;const q=new URLSearchParams(location.search),links=[],add=(name,href,desc)=>links.push([name,href,desc]);if(path==='team.html'){const t=q.get('team')||'';add('All Games',`games.html?team=${encodeURIComponent(t)}`,'Game history');add('ELO History',`elo.html?team1=${encodeURIComponent(t)}`,'Ratings');add('Compare',`compare.html?team1=${encodeURIComponent(t)}`,'Head to head');add('Program Leaderboard','programs.html','All programs');add('Championships','championships.html','Playoff history')}else if(path==='championships.html'){const y=q.get('year')||'';if(y)add(`${y} Season`,`season.html?year=${y}`,'Season yearbook');add('Greatest Seasons','greatest-seasons.html','Historic teams');add('Records','records.html','Record book');add('Program Leaderboard','programs.html','All programs')}else if(path==='games.html'){add('Season Explorer','season.html','Browse by year');add('Scorigami','scorigami.html','Score history');add('Program Leaderboard','programs.html','Program history');add('Team Comparison','compare.html','Compare programs')}else if(path==='records.html'){add('Program Leaderboard','programs.html','All programs');add('Championships','championships.html','Titles and brackets');add('Greatest Seasons','greatest-seasons.html','Top seasons');add('ELO','elo.html','Ratings history')}else if(path==='elo.html'){add('Program Leaderboard','programs.html','All-time context');add('Team Comparison','compare.html','Side by side');add('Teams','teams.html','Team explorer');add('Games','games.html','Game history')}else if(path==='season.html'){const y=q.get('year')||'';add('Championship Brackets',`championships.html?year=${encodeURIComponent(y)}`,'Playoffs');add('Games Database',`games.html?year=${encodeURIComponent(y)}`,'Filter games');add('Greatest Seasons','greatest-seasons.html','Top team seasons');add('Program Leaderboard','programs.html','All programs')}else if(path==='game.html'){const a=q.get('team1')||'',b=q.get('team2')||'',y=yearOf(q.get('date'))||'';add(`${a} Team Page`,`team.html?team=${encodeURIComponent(a)}`,'Program history');add(`${b} Team Page`,`team.html?team=${encodeURIComponent(b)}`,'Program history');add(`${y} Season`,`season.html?year=${y}`,'Season context');add('Series Games',`games.html?search=${encodeURIComponent(a+' vs '+b)}`,'All meetings')}else if(path==='programs.html'){add('Teams','teams.html','Team explorer');add('Championships','championships.html','Titles and brackets');add('ELO','elo.html','Ratings history');add('Greatest Seasons','greatest-seasons.html','Top seasons')}if(!links.length)return;main.insertAdjacentHTML('beforeend',`<section class="rus-related"><h2>Related</h2><div class="rus-related-grid">${links.map(([n,h,d])=>`<a href="${h}">${esc(n)}<span>${esc(d)}</span></a>`).join('')}</div></section>`)}

  function improveGamesPage(){if(path!=='games.html')return;const q=new URLSearchParams(location.search),year=q.get('year'),type=q.get('type'),sort=q.get('sort');let tries=0;const apply=()=>{tries++;const y=document.getElementById('year');if(!y){if(tries<30)setTimeout(apply,100);return}if(year&&[...y.options].some(o=>o.value===year))y.value=year;if(type&&[...document.getElementById('type').options].some(o=>o.value===type))document.getElementById('type').value=type;if(sort&&[...document.getElementById('sort').options].some(o=>o.value===sort))document.getElementById('sort').value=sort;document.getElementById('year').dispatchEvent(new Event('change'))};setTimeout(apply,150);const sync=()=>{const n=new URLSearchParams(),s=document.getElementById('search')?.value.trim(),yr=document.getElementById('year')?.value,tp=document.getElementById('type')?.value,so=document.getElementById('sort')?.value;if(s)n.set('search',s);if(yr&&yr!=='all')n.set('year',yr);if(tp&&tp!=='all')n.set('type',tp);if(so&&so!=='newest')n.set('sort',so);history.replaceState(null,'',`games.html${n.toString()?'?'+n:''}`)};['search','year','type','sort'].forEach(id=>document.getElementById(id)?.addEventListener(id==='search'?'input':'change',()=>setTimeout(sync,0)));const rows=document.getElementById('rows');if(rows){const enhance=()=>{for(const tr of rows.querySelectorAll('tr')){const td=tr.children;if(td.length<4||tr.dataset.rusGameLink)return;const date=td[0].textContent.trim(),a=td[1].textContent.trim(),score=td[2].textContent.trim().split(/[–-]/).map(x=>Number(x.trim())),b=td[3].textContent.trim();if(!date||!a||!b||score.length<2||!Number.isFinite(score[0])||!Number.isFinite(score[1]))continue;const href=gameURL({date,team1:a,score1:score[0],team2:b,score2:score[1]});td[2].innerHTML=`<a class="rus-game-detail-link" href="${href}" title="Open game details">${esc(score[0]+'–'+score[1])}</a>`;tr.dataset.rusGameLink='1'}};new MutationObserver(enhance).observe(rows,{childList:true,subtree:true});enhance()}}

  function setupMeta(){const descriptions={'index.html':'Utah high school football history, records, games, rankings, championships, ELO, simulations and more from Rural Utah Sports.','games.html':'Search Utah high school football game results across more than a century of history.','team.html':'Explore Utah high school football team history, records, seasons, playoffs and ELO.','championships.html':'Explore Utah high school football state champions and historical playoff brackets.','season.html':'Explore a complete Utah high school football season with champions, records and notable games.','game.html':'Open a shareable Utah high school football game result with season and series context.','programs.html':'Compare Utah high school football programs across eras by wins, titles, win percentage and more.'};const desc=descriptions[path]||'Utah high school football history and data from Rural Utah Sports.';let m=document.querySelector('meta[name="description"]');if(!m){m=document.createElement('meta');m.name='description';document.head.appendChild(m)}m.content=desc;const set=(prop,val,attr='property')=>{let el=document.head.querySelector(`meta[${attr}="${prop}"]`);if(!el){el=document.createElement('meta');el.setAttribute(attr,prop);document.head.appendChild(el)}el.content=val};set('og:title',document.title);set('og:description',desc);set('og:type','website');set('og:image',new URL('RUSlogoNew.png',location.href).href);set('twitter:card','summary_large_image','name');set('twitter:title',document.title,'name');set('twitter:description',desc,'name')}
  function init(){ensureStyles();setupSearch();setupMeta();setupHomeSearch();setupHomeCards();setupHomeHistory();improveGamesPage();setTimeout(setupRelated,250)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();