(()=>{
'use strict';
if((location.pathname.split('/').pop()||'').toLowerCase()!=='team.html')return;
const tabs=[['overview','Overview'],['seasons','Seasons'],['playoffs','Playoffs'],['games','Games'],['elo','ELO'],['history','History']];
const sectionMap={'team information':'overview','greatest seasons':'seasons','season-by-season history':'seasons','championship history':'playoffs','schedule by year':'games','elo history':'elo','historical records':'history'};
function addStyles(){if(document.getElementById('rus-team-tabs-style'))return;const s=document.createElement('style');s.id='rus-team-tabs-style';s.textContent=`.rus-team-tabs-shell{margin-top:20px}.rus-team-tabs{position:sticky;top:0;z-index:35;display:flex;gap:6px;overflow-x:auto;background:#0b0b0b;border:1px solid #333;border-top:4px solid #F14D07;border-radius:8px;padding:8px;margin-bottom:16px}.rus-team-tab{flex:1 0 auto;min-width:112px;border:1px solid #333;background:#171717;color:#bbb;border-radius:6px;padding:11px 13px;font-size:12px;font-weight:900;text-transform:uppercase;cursor:pointer;white-space:nowrap;pointer-events:auto!important}.rus-team-tab.active{background:#F14D07;border-color:#F14D07;color:#000}.rus-team-panel[hidden]{display:none!important}.rus-team-panel:not([hidden]){display:block!important}.rus-tab-empty{background:#090909;border:1px solid #333;border-radius:8px;color:#888;padding:35px;text-align:center}.rus-team-panel .history-wrap,.rus-team-panel .record-wrap{max-height:62vh}@media(max-width:700px){.rus-team-tabs{padding:6px;gap:5px}.rus-team-tab{min-width:94px;padding:10px 11px;font-size:11px}.rus-team-panel .history-wrap,.rus-team-panel .record-wrap{max-height:58vh}}`;document.head.appendChild(s)}
function collect(title){const nodes=[title];let n=title.nextSibling;while(n){if(n.nodeType===1&&n.classList?.contains('section-title'))break;if(n.nodeType===1&&n.classList?.contains('rus-timeline-wrap'))break;nodes.push(n);n=n.nextSibling}return nodes}
function wanted(){const q=(new URLSearchParams(location.search).get('tab')||'').toLowerCase();return tabs.some(([k])=>k===q)?q:'overview'}
function show(shell,key,save=true){if(!shell)return;const valid=tabs.some(([k])=>k===key)?key:'overview';for(const b of shell.querySelectorAll('.rus-team-tab')){const on=b.dataset.tab===valid;b.classList.toggle('active',on);b.setAttribute('aria-selected',on?'true':'false');b.tabIndex=on?0:-1}for(const p of shell.querySelectorAll('.rus-team-panel')){const on=p.dataset.tab===valid;p.hidden=!on;p.style.display=on?'block':'none';p.classList.toggle('active',on)}if(save){try{const u=new URL(location.href);if(valid==='overview')u.searchParams.delete('tab');else u.searchParams.set('tab',valid);history.replaceState({},'',u)}catch(e){console.warn('Unable to update team tab URL',e)}}}
function activateButton(button){if(!button)return;const shell=button.closest('.rus-team-tabs-shell');if(!shell)return;show(shell,button.dataset.tab,true)}
window.RUSTeamTabsClick=activateButton;
function build(){addStyles();const page=document.getElementById('page');if(!page||page.dataset.rusTabs==='1')return false;const hero=page.querySelector('.hero'),ach=page.querySelector('.achievement-grid');if(!hero||!ach)return false;page.dataset.rusTabs='1';const shell=document.createElement('section');shell.className='rus-team-tabs-shell';shell.innerHTML=`<div class="rus-team-tabs" role="tablist" aria-label="Team sections">${tabs.map(([k,l])=>`<button class="rus-team-tab" id="rus-tab-${k}" data-tab="${k}" type="button" role="tab" aria-controls="rus-panel-${k}" onclick="window.RUSTeamTabsClick(this)">${l}</button>`).join('')}</div><div class="rus-team-panels">${tabs.map(([k])=>`<section class="rus-team-panel" id="rus-panel-${k}" data-tab="${k}" role="tabpanel" aria-labelledby="rus-tab-${k}" hidden></section>`).join('')}</div>`;ach.insertAdjacentElement('afterend',shell);const panels=Object.fromEntries(tabs.map(([k])=>[k,shell.querySelector(`#rus-panel-${k}`)]));const timeline=page.querySelector('.rus-timeline-wrap');if(timeline)panels.history.appendChild(timeline);const related=page.querySelector(':scope > .rus-related');if(related)panels.overview.appendChild(related);[...page.querySelectorAll(':scope > .section-title')].forEach(title=>{const k=sectionMap[title.textContent.trim().toLowerCase()]||'overview';for(const node of collect(title))panels[k].appendChild(node)});for(const [k] of tabs)if(!panels[k].children.length)panels[k].innerHTML='<div class="rus-tab-empty">No data available in this section.</div>';
const late=new MutationObserver(()=>{const t=page.querySelector(':scope > .rus-timeline-wrap');if(t)panels.history.appendChild(t);const r=page.querySelector(':scope > .rus-related');if(r)panels.overview.appendChild(r)});late.observe(page,{childList:true});
for(const button of shell.querySelectorAll('.rus-team-tab'))button.addEventListener('click',()=>activateButton(button));
shell.addEventListener('click',e=>{const b=e.target.closest?.('.rus-team-tab');if(!b||!shell.contains(b))return;activateButton(b)});
shell.addEventListener('keydown',e=>{const b=e.target.closest?.('.rus-team-tab');if(!b||(e.key!=='ArrowRight'&&e.key!=='ArrowLeft'))return;e.preventDefault();const buttons=[...shell.querySelectorAll('.rus-team-tab')],i=buttons.indexOf(b),step=e.key==='ArrowRight'?1:-1,next=buttons[(i+step+buttons.length)%buttons.length];next.focus();show(shell,next.dataset.tab,true)});
show(shell,wanted(),false);window.RUSTeamTabs={show:key=>show(shell,key,true)};return true}
function start(){let tries=0;const wait=()=>{if(build()||++tries>300)return;setTimeout(wait,100)};setTimeout(wait,150)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();