(()=>{
'use strict';
if((location.pathname.split('/').pop()||'').toLowerCase()!=='team.html')return;
const tabs=[['overview','Overview'],['seasons','Seasons'],['playoffs','Playoffs'],['games','Games'],['elo','ELO'],['history','History']];
const sectionMap={'team information':'overview','greatest seasons':'seasons','season-by-season history':'seasons','championship history':'playoffs','schedule by year':'games','elo history':'elo','historical records':'history'};
function addStyles(){if(document.getElementById('rus-team-tabs-style'))return;const s=document.createElement('style');s.id='rus-team-tabs-style';s.textContent=`.rus-team-tabs-shell{margin-top:20px}.rus-team-tabs{position:sticky;top:0;z-index:35;display:flex;gap:6px;overflow-x:auto;background:#0b0b0b;border:1px solid #333;border-top:4px solid #F14D07;border-radius:8px;padding:8px;margin-bottom:16px}.rus-team-tab{flex:1 0 auto;min-width:112px;border:1px solid #333;background:#171717;color:#bbb;border-radius:6px;padding:11px 13px;font-size:12px;font-weight:900;text-transform:uppercase;cursor:pointer;white-space:nowrap}.rus-team-tab.active{background:#F14D07;border-color:#F14D07;color:#000}.rus-team-panel{display:none}.rus-team-panel.active{display:block}.rus-tab-empty{background:#090909;border:1px solid #333;border-radius:8px;color:#888;padding:35px;text-align:center}.rus-team-panel .history-wrap,.rus-team-panel .record-wrap{max-height:62vh}@media(max-width:700px){.rus-team-tabs{padding:6px;gap:5px}.rus-team-tab{min-width:94px;padding:10px 11px;font-size:11px}.rus-team-panel .history-wrap,.rus-team-panel .record-wrap{max-height:58vh}}`;document.head.appendChild(s)}
function collect(title){const nodes=[title];let n=title.nextSibling;while(n){if(n.nodeType===1&&n.classList?.contains('section-title'))break;if(n.nodeType===1&&n.classList?.contains('rus-timeline-wrap'))break;nodes.push(n);n=n.nextSibling}return nodes}
function show(shell,key){const valid=tabs.some(([k])=>k===key)?key:'overview';shell.querySelectorAll('.rus-team-tab').forEach(b=>{const on=b.dataset.tab===valid;b.classList.toggle('active',on);b.setAttribute('aria-selected',on?'true':'false')});shell.querySelectorAll('.rus-team-panel').forEach(p=>p.classList.toggle('active',p.dataset.tab===valid))}
function build(){addStyles();const page=document.getElementById('page');if(!page||page.dataset.rusTabs==='1')return false;const hero=page.querySelector('.hero'),ach=page.querySelector('.achievement-grid');if(!hero||!ach)return false;page.dataset.rusTabs='1';const shell=document.createElement('section');shell.className='rus-team-tabs-shell';shell.innerHTML=`<div class="rus-team-tabs" role="tablist">${tabs.map(([k,l])=>`<button class="rus-team-tab" data-tab="${k}" type="button">${l}</button>`).join('')}</div><div class="rus-team-panels">${tabs.map(([k])=>`<section class="rus-team-panel" data-tab="${k}"></section>`).join('')}</div>`;ach.insertAdjacentElement('afterend',shell);const panels=Object.fromEntries(tabs.map(([k])=>[k,shell.querySelector(`[data-tab="${k}"].rus-team-panel`)]));const timeline=page.querySelector('.rus-timeline-wrap');if(timeline)panels.history.appendChild(timeline);[...page.querySelectorAll(':scope > .section-title')].forEach(title=>{const key=sectionMap[title.textContent.trim().toLowerCase()]||'overview';for(const node of collect(title))panels[key].appendChild(node)});for(const [k] of tabs)if(!panels[k].children.length)panels[k].innerHTML='<div class="rus-tab-empty">No data available in this section.</div>';shell.querySelectorAll('.rus-team-tab').forEach(b=>b.addEventListener('click',()=>show(shell,b.dataset.tab)));show(shell,'overview');return true}
function start(){let tries=0;const wait=()=>{if(build()||++tries>80)return;setTimeout(wait,125)};setTimeout(wait,450)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();