(()=>{
'use strict';
if(window.__rusTeamStatsLoaded)return;window.__rusTeamStatsLoaded=true;
if((location.pathname.split('/').pop()||'').toLowerCase()!=='team.html')return;
const qs=new URLSearchParams(location.search),team=qs.get('team')||'',season=Number(qs.get('season')||2026);if(!team||![2025,2026].includes(season))return;
const norm=v=>String(v??'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'');
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const fmt=(v,d=1)=>v===null||v===undefined||!Number.isFinite(Number(v))?'—':Number(v).toFixed(d);
const int=v=>v===null||v===undefined||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString();
const rank=v=>v?`#${v}`:'—';

const style=document.createElement('style');style.id='rus-team-stats-style';style.textContent=`
.rus-team-stats{margin:0 0 30px}.rus-team-stats-title{border-left:6px solid #F14D07;padding-left:12px;margin:0 0 12px;text-transform:uppercase;font-size:27px}.rus-team-stats-sub{color:#888;font-size:11px;line-height:1.5;margin:-4px 0 12px}.rus-ts-hero{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;margin-bottom:11px}.rus-ts-card{background:#000;border:1px solid #333;border-radius:7px;padding:14px;text-align:center}.rus-ts-card strong{display:block;font-size:23px;color:#F14D07}.rus-ts-card span{display:block;color:#888;font-size:9px;text-transform:uppercase;font-weight:900;margin-top:5px}.rus-ts-details{background:#050505;border:1px solid #333;border-radius:8px;margin:0 0 9px;overflow:hidden}.rus-ts-details>summary{cursor:pointer;list-style:none;padding:13px 15px;font-weight:900;text-transform:uppercase;font-size:13px;background:#141414;display:flex;justify-content:space-between;align-items:center}.rus-ts-details>summary::-webkit-details-marker{display:none}.rus-ts-details>summary:after{content:'+';color:#F14D07;font-size:18px}.rus-ts-details[open]>summary:after{content:'−'}.rus-ts-body{padding:12px}.rus-ts-group-title{font-size:11px;color:#aaa;font-weight:900;text-transform:uppercase;margin:3px 0 7px}.rus-ts-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:7px;margin-bottom:12px}.rus-ts-mini{background:#111;border:1px solid #292929;border-radius:6px;padding:10px;text-align:center;min-width:0}.rus-ts-mini strong{display:block;font-size:16px}.rus-ts-mini span{display:block;color:#777;font-size:8px;text-transform:uppercase;font-weight:900;margin-top:4px;line-height:1.2}.rus-ts-ranking{display:grid;grid-template-columns:minmax(150px,1fr) repeat(3,minmax(85px,.42fr));align-items:center;border-bottom:1px solid #272727;padding:10px 8px;font-size:11px}.rus-ts-ranking:last-child{border-bottom:0}.rus-ts-ranking b{font-size:11px}.rus-ts-ranking span{text-align:center;color:#aaa}.rus-ts-ranking strong{color:#F14D07}.rus-ts-note{font-size:10px;line-height:1.5;color:#777;margin-top:9px}.rus-ts-empty{background:#000;border:1px solid #333;border-radius:7px;padding:18px;color:#888;font-size:11px}
@media(max-width:900px){.rus-ts-grid{grid-template-columns:repeat(3,1fr)}}
@media(max-width:600px){.rus-team-stats-title{font-size:22px}.rus-ts-hero{grid-template-columns:repeat(2,1fr)}.rus-ts-card{padding:11px 8px}.rus-ts-card strong{font-size:20px}.rus-ts-grid{grid-template-columns:repeat(2,1fr)}.rus-ts-details>summary{padding:12px;font-size:12px}.rus-ts-body{padding:9px}.rus-ts-ranking{grid-template-columns:1fr repeat(3,58px);font-size:9px;padding:9px 3px}.rus-ts-ranking b{font-size:10px}.rus-ts-ranking span{font-size:9px}}
`;document.head.appendChild(style);

function mini(value,label,d=null){const shown=d===null?int(value):fmt(value,d);return `<div class="rus-ts-mini"><strong>${shown}</strong><span>${esc(label)}</span></div>`}
function rankRow(x,key){const r=x.rankings?.[key];if(!r||(!r.state&&!r.class&&!r.region))return'';return `<div class="rus-ts-ranking"><b>${esc(r.label||key)}</b><span>State <strong>${rank(r.state)}</strong></span><span>${esc(x.classification||'Class')} <strong>${rank(r.class)}</strong></span><span>${esc(x.region||'Region')} <strong>${rank(r.region)}</strong></span></div>`}
function details(title,body,open){return `<details class="rus-ts-details" ${open?'open':''}><summary>${esc(title)}</summary><div class="rus-ts-body">${body}</div></details>`}
function render(x,method){
  const hasOff=x.categories?.passing||x.categories?.rushing||x.categories?.receiving;
  const desktop=!matchMedia('(max-width:600px)').matches;
  const overview=`<div class="rus-ts-grid">${mini(x.games,'Games')}${mini(x.pointsFor,'Points For')}${mini(x.pointsAgainst,'Points Allowed')}${mini(x.ppg,'Points / Game',1)}${mini(x.pointsAllowedPerGame,'Allowed / Game',1)}${mini(x.scoringMargin,'Scoring Margin',1)}${mini(x.totalOffense,'Total Offense')}${mini(x.totalYardsPerGame,'Total Yards / Game',1)}${mini(x.yardsPerPlay,'Yards / Play',2)}${mini(x.passing.td,'Pass TD')}${mini(x.rushing.td,'Rush TD')}${mini(x.defense.interceptions,'Defensive INT')}</div>`;
  const passing=x.categories?.passing?`<div class="rus-ts-group-title">Passing</div><div class="rus-ts-grid">${mini(x.passing.completions,'Completions')}${mini(x.passing.attempts,'Attempts')}${mini(x.passing.compPct,'Completion %',1)}${mini(x.passing.yards,'Pass Yards')}${mini(x.passing.yardsPerGame,'Pass Yards / Game',1)}${mini(x.passing.yardsPerAttempt,'Yards / Attempt',2)}${mini(x.passing.td,'Pass TD')}${mini(x.passing.interceptions,'INT Thrown')}</div>`:'';
  const rushing=x.categories?.rushing?`<div class="rus-ts-group-title">Rushing</div><div class="rus-ts-grid">${mini(x.rushing.carries,'Carries')}${mini(x.rushing.yards,'Rush Yards')}${mini(x.rushing.yardsPerGame,'Rush Yards / Game',1)}${mini(x.rushing.yardsPerCarry,'Yards / Carry',2)}${mini(x.rushing.td,'Rush TD')}</div>`:'';
  const receiving=x.categories?.receiving?`<div class="rus-ts-group-title">Receiving</div><div class="rus-ts-grid">${mini(x.receiving.receptions,'Receptions')}${mini(x.receiving.yards,'Receiving Yards')}${mini(x.receiving.yardsPerGame,'Receiving Yards / Game',1)}${mini(x.receiving.yardsPerCatch,'Yards / Catch',2)}${mini(x.receiving.td,'Receiving TD')}</div>`:'';
  const offense=hasOff?`${passing}${rushing}${receiving}<div class="rus-ts-note">Receiving yards are shown separately but are not added to total offense, because those yards are already included in passing yards.</div>`:'<div class="rus-ts-empty">No reported offensive player statistics are available for this season.</div>';
  const defense=x.categories?.defense?`<div class="rus-ts-grid">${mini(x.pointsAgainst,'Points Allowed')}${mini(x.pointsAllowedPerGame,'Allowed / Game',1)}${mini(x.defense.tackles,'Tackles')}${mini(x.defense.sacks,'Sacks',1)}${mini(x.defense.interceptions,'Interceptions')}${mini(x.defense.td,'Defensive TD')}${mini(x.defense.returnTd,'Return TD')}</div>`:`<div class="rus-ts-grid">${mini(x.pointsAgainst,'Points Allowed')}${mini(x.pointsAllowedPerGame,'Allowed / Game',1)}</div><div class="rus-ts-note">Detailed defensive player statistics have not been reported for this team.</div>`;
  const ranks=['ppg','pointsAllowedPerGame','scoringMargin','totalYardsPerGame','yardsPerPlay','rushingYardsPerGame','passingYardsPerGame','sacks','defensiveInterceptions'].map(k=>rankRow(x,k)).join('')||'<div class="rus-ts-empty">Not enough reported data to rank this team yet.</div>';
  const box=document.createElement('section');box.id='rusTeamStats';box.className='rus-team-stats';box.innerHTML=`<h2 class="rus-team-stats-title">${season} Team Stats</h2><div class="rus-team-stats-sub">${esc(x.record||'—')} • ${esc(x.classification||'—')}${x.region?' • '+esc(x.region):''} • Calculated from reported season player stats and completed game finals.</div><div class="rus-ts-hero"><div class="rus-ts-card"><strong>${fmt(x.ppg,1)}</strong><span>Points / Game</span></div><div class="rus-ts-card"><strong>${fmt(x.totalYardsPerGame,1)}</strong><span>Total Yards / Game</span></div><div class="rus-ts-card"><strong>${fmt(x.rushing.yardsPerGame,1)}</strong><span>Rush Yards / Game</span></div><div class="rus-ts-card"><strong>${fmt(x.passing.yardsPerGame,1)}</strong><span>Pass Yards / Game</span></div></div>${details('Overview',overview,desktop)}${details('Offense',offense,desktop)}${details('Defense',defense,desktop)}${details('Team Rankings',ranks,desktop)}<div class="rus-ts-note">${esc(method?.note||'Team statistics are based on reported data; missing statistics are not estimated.')}</div>`;
  const dash=document.getElementById('rusTeamDashboard'),hero=document.querySelector('#page .hero');
  if(dash)dash.insertAdjacentElement('afterend',box);else if(hero)hero.insertAdjacentElement('afterend',box);else document.getElementById('page')?.prepend(box);
}
async function build(){
  if(document.getElementById('rusTeamStats'))return true;
  if(!document.querySelector('#page .hero'))return false;
  try{
    const r=await fetch(`team-stats-${season}.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)return false;const data=await r.json();
    const hit=Object.values(data.teams||{}).find(x=>norm(x.team)===norm(team));if(!hit)return false;render(hit,data.method);return true;
  }catch(e){console.warn('Team stats unavailable',e);return false}
}
let tries=0;const timer=setInterval(async()=>{tries++;if(await build()||tries>80)clearInterval(timer)},150);
})();
