(()=>{
'use strict';
if((location.pathname.split('/').pop()||'').toLowerCase()!=='upsets.html')return;
const root=document.getElementById('featureRoot');if(!root)return;
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const norm=v=>String(v??'').trim().toUpperCase().replace(/\s+/g,' ');
const num=v=>{if(v===null||v===undefined||String(v).trim()==='')return null;const n=Number(v);return Number.isFinite(n)?n:null};
const get=async(name,fallback=null)=>{try{const r=await fetch(name+'?v='+Date.now(),{cache:'no-store'});return r.ok?await r.json():fallback}catch{return fallback}};
const fmtDate=d=>{const n=Date.parse(String(d||''));return Number.isFinite(n)?new Date(n).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):String(d||'')};
const yearOf=v=>{const m=String(v||'').match(/(20\d{2})/);return m?Number(m[1]):null};
function teamPill(name,map){const t=map.get(norm(name)),bg=t?.backgroundColor||'#222',fg=t?.textColor||'#fff';return '<a class="team-pill" style="--bg:'+esc(bg)+';--fg:'+esc(fg)+'" href="team.html?team='+encodeURIComponent(t?.team||name)+'">'+esc(t?.team||name)+'</a>'}
function addStyles(){if(document.getElementById('rus-upset-mode-style'))return;const s=document.createElement('style');s.id='rus-upset-mode-style';s.textContent='.upset-modes{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 14px}.upset-mode{appearance:none;border:1px solid #3b3b3b;background:#151515;color:#aaa;border-radius:8px;padding:10px 13px;font-size:10px;font-weight:1000;text-transform:uppercase;letter-spacing:.45px;cursor:pointer}.upset-mode.active{background:#F14D07;color:#000;border-color:#F14D07}.upset-final{white-space:nowrap}.upset-line{font-weight:1000;color:#F14D07;white-space:nowrap}@media(max-width:700px){.upset-modes{display:grid;grid-template-columns:1fr 1fr}.upset-mode{min-height:44px}.upset-line,.upset-final{white-space:normal}}';document.head.appendChild(s)}
function fallbackElo(changes,utah){const rows=[];for(const g of Object.values(changes?.games||{})){const a=num(g.awayScore),b=num(g.homeScore),ae=num(g.away?.eloBefore),he=num(g.home?.eloBefore);if([a,b,ae,he].some(x=>x===null)||a===b)continue;const ak=norm(g.awayTeam),hk=norm(g.homeTeam);if(!utah.has(ak)||!utah.has(hk))continue;const awayWon=a>b,winner=awayWon?ak:hk,loser=awayWon?hk:ak,we=awayWon?ae:he,le=awayWon?he:ae;if(we>=le)continue;rows.push({season:yearOf(g.date)||2026,date:g.date,winner,loser,margin:Math.abs(a-b),winnerElo:we,loserElo:le,eloGap:le-we,winnerChance:1/(1+Math.pow(10,(le-we)/400))})}return rows.sort((a,b)=>b.eloGap-a.eloGap)}
function fallbackSpread(weekly){const rows=[];for(const g of weekly?.games||[]){const pa=num(g.awayScore),rh=num(g.homeScore),aa=num(g.actualAway),ah=num(g.actualHome);if([pa,rh,aa,ah].some(x=>x===null)||aa===ah)continue;const ph=rh+3;if(pa===ph)continue;const favorite=pa>ph?g.awayTeam:g.homeTeam,winner=aa>ah?g.awayTeam:g.homeTeam;if(norm(favorite)===norm(winner))continue;const spread=Math.abs(pa-ph);rows.push({season:yearOf(g.date),date:g.date,awayTeam:g.awayTeam,homeTeam:g.homeTeam,winner,favorite,spread,lineLabel:favorite+' -'+spread,projectedAway:pa,projectedHome:ph,projectedTotal:pa+ph,actualAway:aa,actualHome:ah,finalMargin:Math.abs(aa-ah)})}return rows.sort((a,b)=>Number(b.spread)-Number(a.spread))}
async function run(){
 addStyles();
 root.innerHTML='<div class="loading">Building upset trackers…</div>';
 const [spreadHistory,eloHistory,teams,changes,weekly]=await Promise.all([get('spread-upsets-history.json',{rows:[]}),get('upsets-history.json'),get('teams-data.json',[]),get('elo-game-changes-2026.json',{}),get('weekly-simulation.json',{games:[]})]);
 const teamMap=new Map((teams||[]).map(t=>[norm(t.team),t])),utah=new Set(teamMap.keys());
 const spreadRows=(Array.isArray(spreadHistory?.rows)&&spreadHistory.rows.length?spreadHistory.rows:fallbackSpread(weekly)).slice().sort((a,b)=>Number(b.spread)-Number(a.spread));
 const eloRows=(Array.isArray(eloHistory?.rows)?eloHistory.rows:fallbackElo(changes,utah)).filter(r=>utah.has(norm(r.winner))&&utah.has(norm(r.loser))).sort((a,b)=>Number(b.eloGap)-Number(a.eloGap));
 const spreadSeasons=(spreadHistory?.seasons||[...new Set(spreadRows.map(r=>Number(r.season)).filter(Number.isFinite))]).slice().sort((a,b)=>b-a);
 const eloSeasons=(eloHistory?.seasons||[...new Set(eloRows.map(r=>Number(r.season)).filter(Number.isFinite))]).slice().sort((a,b)=>b-a);
 root.innerHTML='<div class="upset-modes"><button class="upset-mode active" data-mode="spread">RUS Line Upsets</button><button class="upset-mode" data-mode="elo">ELO Upsets</button></div><div id="upsetNote" class="feature-note"></div><div class="toolbar"><div class="field"><label for="upsetSeason">Season</label><select id="upsetSeason"></select></div><div class="field"><label for="upsetLimit">Show</label><select id="upsetLimit"><option value="25">Top 25</option><option value="50" selected>Top 50</option><option value="100">Top 100</option></select></div></div><div id="upsetSummary"></div><div id="upsetTable"></div>';
 const note=document.getElementById('upsetNote'),seasonSel=document.getElementById('upsetSeason'),limitSel=document.getElementById('upsetLimit'),summary=document.getElementById('upsetSummary'),out=document.getElementById('upsetTable');
 let mode='spread';
 function rowsForMode(){return mode==='spread'?spreadRows:eloRows}
 function seasonsForMode(){return mode==='spread'?spreadSeasons:eloSeasons}
 function fillSeasons(){const current=seasonSel.value,seasons=seasonsForMode();seasonSel.innerHTML='<option value="all">All Time</option>'+seasons.map(y=>'<option value="'+y+'">'+y+'</option>').join('');if(current&&[...seasonSel.options].some(o=>o.value===current))seasonSel.value=current;else if(seasons.includes(2026))seasonSel.value='2026';else seasonSel.value=seasons.length?String(seasons[0]):'all'}
 function spreadTable(rows){return '<div class="table-wrap"><table><thead><tr><th>#</th><th>Date</th><th class="left">Upset Winner</th><th class="left">Favorite</th><th>RUS Line</th><th>Final</th><th>Won By</th></tr></thead><tbody>'+rows.map((r,i)=>'<tr><td class="rank">'+(i+1)+'</td><td>'+esc(fmtDate(r.date))+'</td><td class="left">'+teamPill(r.winner,teamMap)+'</td><td class="left">'+teamPill(r.favorite,teamMap)+'</td><td class="upset-line">'+esc(r.lineLabel||((r.favorite||'')+' -'+(Number(r.spread)||0)))+'</td><td class="upset-final">'+teamPill(r.awayTeam,teamMap)+' '+esc(r.actualAway)+'–'+esc(r.actualHome)+' '+teamPill(r.homeTeam,teamMap)+'</td><td>'+esc(Number(r.finalMargin)||0)+'</td></tr>').join('')+'</tbody></table></div>'}
 function eloTable(rows){return '<div class="table-wrap"><table><thead><tr><th>#</th><th>Date</th><th class="left">Upset Winner</th><th class="left">Favorite</th><th>Won By</th><th>Pregame ELO Gap</th><th>Winner Chance</th></tr></thead><tbody>'+rows.map((r,i)=>'<tr><td class="rank">'+(i+1)+'</td><td>'+esc(fmtDate(r.date))+'</td><td class="left">'+teamPill(r.winner,teamMap)+'</td><td class="left">'+teamPill(r.loser,teamMap)+'</td><td>'+esc(Number(r.margin)||0)+'</td><td><strong>'+Math.round(Number(r.eloGap)||0)+'</strong></td><td>'+(((Number(r.winnerChance)||0)*100).toFixed(1))+'%</td></tr>').join('')+'</tbody></table></div>'}
 function render(){const season=seasonSel.value,limit=Number(limitSel.value)||50,all=rowsForMode().filter(r=>season==='all'||String(r.season)===season),shown=all.slice(0,limit);if(mode==='spread'){note.innerHTML='<strong>Point-spread upset:</strong> the team listed as the underdog by the published RUS line won the game outright. Pick’em games are not counted. RUS lines are model projections, not sportsbook or wagering lines.';summary.innerHTML='<h2 class="section-title">'+(season==='all'?'All-Time':'Season '+esc(season))+' RUS Line Upsets</h2><p class="muted" style="margin:-8px 0 14px">'+all.length.toLocaleString()+' point-spread upset'+(all.length===1?'':'s')+' found'+(all.length>limit?' • showing top '+limit:'')+'. Ranked by how many points the winner was an underdog.</p>';out.innerHTML=shown.length?spreadTable(shown):'<div class="empty">No RUS line upsets are available for this season yet.</div>'}else{note.innerHTML='<strong>Utah vs. Utah only.</strong> ELO upsets are ranked by the pregame RUS ELO difference: the larger the rating gap a lower-rated winner overcame, the bigger the upset.';summary.innerHTML='<h2 class="section-title">'+(season==='all'?'All-Time':'Season '+esc(season))+' ELO Upsets</h2><p class="muted" style="margin:-8px 0 14px">'+all.length.toLocaleString()+' Utah-vs-Utah ELO upset'+(all.length===1?'':'s')+' found'+(all.length>limit?' • showing top '+limit:'')+'.</p>';out.innerHTML=shown.length?eloTable(shown):'<div class="empty">No Utah-vs-Utah ELO upsets are available for this season yet.</div>'}}
 document.querySelectorAll('.upset-mode').forEach(btn=>btn.addEventListener('click',()=>{mode=btn.dataset.mode||'spread';document.querySelectorAll('.upset-mode').forEach(b=>b.classList.toggle('active',b===btn));fillSeasons();render()}));
 seasonSel.onchange=render;limitSel.onchange=render;fillSeasons();render();
}
run().catch(e=>{console.error(e);root.innerHTML='<div class="empty">Upset data could not be loaded. Try refreshing in a moment.</div>'});
})();
