import fs from 'node:fs';

const DETAILS='deseret-game-details-2025.json',ROSTERS='deseret-rosters-stats-2025.json',OUT='player-game-stats-2025.json';
const clean=v=>String(v??'').trim(),compact=v=>clean(v).toUpperCase().replace(/[^A-Z0-9]/g,''),slug=v=>clean(v).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
const aliases={CEDAR:'CEDARCITY',CEDARCITY:'CEDARCITY',GRANDCOUNTY:'GRAND',GUNNISON:'GUNNISONVALLEY',MONUMENTVAL:'MONUMENTVALLEY',MAPLEMTN:'MAPLEMOUNTAIN',AMERICANLEADERSHIP:'ALA',AMERICANLEADERSHIPACADEMY:'ALA',STJOSEPH:'SAINTJOSEPH',UTAHMILITARYCAMPWILLIAMS:'UMALEHI',UTAHMILITARYHILLFIELD:'UMAHILLFIELD'};const canon=v=>aliases[compact(v)]||compact(v);
function playerId(team,no,name){return `${slug(team)}-${slug(no||'x')}-${slug(name||'unknown')}`}
function bits(v){const p=clean(v).replace(/[^A-Za-z0-9'’.-]+/g,' ').split(/\s+/).filter(Boolean);return{first:compact(p[0]||''),initial:compact((p[0]||'').charAt(0)),last:compact(p[p.length-1]||'')}}
function rosterIndex(t){const all=[],byNo=new Map();for(const p of t?.roster||[]){const x={...p,bits:bits(p.name)};all.push(x);const n=compact(p.number);if(n){if(!byNo.has(n))byNo.set(n,[]);byNo.get(n).push(x)}}return{all,byNo}}
function match(idx,no,name){const n=compact(no),b=bits(name),rows=n?(idx.byNo.get(n)||[]):idx.all;let best=null,score=0;for(const p of rows){let s=0;if(n&&compact(p.number)===n)s+=5;if(b.last&&p.bits.last===b.last)s+=7;else if(b.last&&p.bits.last&&(b.last.endsWith(p.bits.last)||p.bits.last.endsWith(b.last)))s+=3;if(b.first&&p.bits.first===b.first)s+=2;if(b.initial&&p.bits.initial===b.initial)s+=1;if(s>score){score=s;best=p}}return{player:best,score}}
function cleanName(v){return clean(v).replace(/^\s*[A-Z]\s*\.\s*/i,'').replace(/\s+/g,' ')}
function parseRows(table){const h=(table.headers||[]).map(clean),hu=h.map(compact);let noI=hu.findIndex(x=>x==='NO'||x==='NUMBER'||x==='#'),nameI=hu.findIndex(x=>x==='PLAYER'||x.includes('PLAYERNAME'));if(noI<0)noI=0;if(nameI<0)nameI=1;const out=[];for(const row of table.rows||[]){const r=row.map(clean),name=cleanName(r[nameI]||'');if(!name||compact(name)==='PLAYER')continue;const values={};for(let i=0;i<h.length;i++){if(i===noI||i===nameI)continue;values[h[i]||`Stat ${i+1}`]=r[i]||''}out.push({number:r[noI]||'',name,category:table.category||'Stats',values})}return out}
function teamScore(g,team){if(canon(team)===canon(g.teamA))return g.actualScoreA;if(canon(team)===canon(g.teamB))return g.actualScoreB;return null}
if(!fs.existsSync(DETAILS)||!fs.existsSync(ROSTERS))throw new Error('2025 game details or roster archive missing');const details=JSON.parse(fs.readFileSync(DETAILS,'utf8')).games||{},rosters=JSON.parse(fs.readFileSync(ROSTERS,'utf8')).teams||{};const rosterKeys=Object.keys(rosters),teams={};let gameCount=0,statRows=0,matchedRows=0;
for(const g of Object.values(details)){const participants=[g.teamA,g.teamB].filter(Boolean);for(const team of participants){const rk=rosterKeys.find(k=>canon(k)===canon(team));if(!rk)continue;const idx=rosterIndex(rosters[rk]),players={};for(const table of g.stats||[])for(const raw of parseRows(table)){const m=match(idx,raw.number,raw.name);if(m.score<7)continue;const p=m.player,id=p?.playerId||playerId(team,raw.number,raw.name),name=p?.name||raw.name;if(!players[id])players[id]={playerId:id,number:p?.number||raw.number,name,rosterMatched:!!p,statLines:[],scoringPlays:[]};players[id].statLines.push({category:raw.category,values:raw.values});statRows++;if(p)matchedRows++}for(const p of Object.values(players)){const b=bits(p.name);p.scoringPlays=(g.scoringPlays||[]).filter(x=>b.last&&compact(x).includes(b.last)).slice(0,12)}if(!Object.keys(players).length)continue;const opponent=canon(team)===canon(g.teamA)?g.teamB:g.teamA;if(!teams[team])teams[team]={team,games:[]};teams[team].games.push({date:g.date,opponent,teamScore:teamScore(g,team),opponentScore:teamScore(g,opponent),url:g.url||'',players:Object.values(players),scoringPlays:g.scoringPlays||[]});gameCount++}}
for(const t of Object.values(teams))t.games.sort((a,b)=>String(a.date).localeCompare(String(b.date)));const out={season:2025,updatedAt:new Date().toISOString(),summary:{teams:Object.keys(teams).length,teamGames:gameCount,statRows,rosterMatchedRows:matchedRows},teams};fs.writeFileSync(OUT,JSON.stringify(out,null,2)+'\n');console.log('2025 player game stats',out.summary);
