import fs from 'node:fs';

const SOURCE='deseret-team-data-2025.json',OUT='deseret-game-details-2025.json';
const clean=v=>String(v??'').trim(),compact=v=>clean(v).toUpperCase().replace(/[^A-Z0-9]/g,'');
function decode(s){return String(s||'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16)))}
function htmlText(html){return decode(String(html||'')).replace(/<(script|style|noscript|svg)\b[^>]*>[\s\S]*?<\/\1>/gi,' ').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/(?:p|div|li|tr|h[1-6]|section|article)>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/[ \t]+/g,' ').replace(/\n\s+/g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
const cellText=html=>htmlText(html).replace(/\s+/g,' ').trim();
function tables(html){const out=[];const re=/<table\b[^>]*>([\s\S]*?)<\/table>/gi;let m;while((m=re.exec(html))){const rows=[];const rr=/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi;let rm;while((rm=rr.exec(m[1]))){const cells=[];const cr=/<(?:th|td)\b[^>]*>([\s\S]*?)<\/(?:th|td)>/gi;let cm;while((cm=cr.exec(rm[1])))cells.push(cellText(cm[1]));if(cells.some(Boolean))rows.push(cells)}if(rows.length)out.push({rows,context:htmlText(html.slice(Math.max(0,m.index-1800),m.index))})}return out}
function findBox(ts){for(const t of ts){const hi=t.rows.findIndex(r=>{const v=r.map(x=>compact(x));return ['Q1','Q2','Q3','Q4','TOTAL'].every(x=>v.includes(x))});if(hi<0)continue;const headers=t.rows[hi],rows=[];for(const r of t.rows.slice(hi+1)){if(r.length<6)continue;const s=r.slice(-5);if(!s.every(v=>/^\d+$/.test(clean(v))))continue;rows.push({team:r.slice(0,-5).filter(Boolean).join(' ').replace(/^@\s*/,''),quarters:s.slice(0,4).map(Number),total:Number(s[4])});if(rows.length===2)break}if(rows.length===2)return{periods:headers.slice(-5,-1),rows}}return null}
function category(h){const j=h.map(x=>compact(x)).join('|');if(j.includes('COMPATT')&&j.includes('YARD'))return'Passing';if(j.includes('CARRIES')&&j.includes('YARD'))return'Rushing';if(j.includes('RECEPTIONS')&&j.includes('YARD'))return'Receiving';if(j.includes('TACKLES')||j.includes('SACKS')||j.includes('PASSINT')||j.includes('INTERCEPTIONS'))return'Defense/Special Teams';if(j.includes('FG')&&j.includes('PAT'))return'Kicking';return''}
function extractStats(ts){const out=[];for(const t of ts){const hi=t.rows.findIndex(r=>category(r));if(hi<0)continue;const headers=t.rows[hi].map(clean),cat=category(headers);if(!cat)continue;const rows=t.rows.slice(hi+1).map(r=>r.map(clean)).filter(r=>r.some(Boolean)).filter(r=>!category(r)).slice(0,120);if(rows.length)out.push({category:cat,headers,rows,context:t.context})}return out}
function scoring(html){const m=/Scoring(?:\s|<[^>]+>)*Summary/i.exec(html);if(!m)return[];let seg=html.slice(m.index,m.index+60000),out=[];const re=/<li\b[^>]*>([\s\S]*?)<\/li>/gi;let x;while((x=re.exec(seg))){const t=cellText(x[1]).trim();if(t&&(/—/.test(t)||/\b\d{1,2}:\d{2}\b/.test(t)))out.push(t)}return [...new Set(out)].slice(0,60)}
function urlTeams(url){const m=String(url).match(/\/game\/(\d{4}-\d{2}-\d{2})\/(.+?)-football-vs-(.+?)-football\/\d+/i);if(!m)return{date:'',awaySlug:'',homeSlug:''};const human=s=>s.split('-').filter(Boolean).map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(' ');return{date:m[1],awaySlug:m[2],homeSlug:m[3],awayTeam:human(m[2]),homeTeam:human(m[3])}}
async function fetchHtml(url){const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (compatible; RuralUtahSports/1.0; +https://ruralutahsports.github.io/)'},redirect:'follow',signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.text()}
if(!fs.existsSync(SOURCE))throw new Error(`${SOURCE} missing`);const source=JSON.parse(fs.readFileSync(SOURCE,'utf8'));const unique=new Map();for(const t of Object.values(source.teams||{}))for(const g of t.schedule||[])if(g.gameUrl)unique.set(g.gameUrl,g);const jobs=[...unique.entries()];let prior={games:{}};try{prior=JSON.parse(fs.readFileSync(OUT,'utf8'))}catch{}const games={...(prior.games||{})};let next=0,fetched=0,reused=0,failures=0,withStats=0,withBox=0;
async function one(url,g){if(games[url]?.fetchedAt){reused++;return}try{const html=await fetchHtml(url),ts=tables(html),u=urlTeams(url),boxScore=findBox(ts),stats=extractStats(ts),scoringPlays=scoring(html);games[url]={url,date:u.date||g.date,awayTeam:u.awayTeam||g.awayTeam||g.teamA,homeTeam:u.homeTeam||g.homeTeam||g.teamB,teamA:g.teamA,teamB:g.teamB,actualScoreA:g.actualScoreA,actualScoreB:g.actualScoreB,boxScore,stats,scoringPlays,fetchedAt:new Date().toISOString()};fetched++;if(stats.length)withStats++;if(boxScore)withBox++}catch(e){failures++;console.warn(`${url}: ${e.message}`)}}
async function worker(){while(true){const i=next++;if(i>=jobs.length)return;await one(...jobs[i]);await new Promise(r=>setTimeout(r,70))}}
await Promise.all(Array.from({length:6},()=>worker()));const out={season:2025,updatedAt:new Date().toISOString(),summary:{uniqueGames:jobs.length,fetched,reused,failures,gamesWithStats:withStats,gamesWithBoxScore:withBox},games};fs.writeFileSync(OUT,JSON.stringify(out,null,2)+'\n');console.log('2025 game details',out.summary);if(Object.keys(games).length<Math.floor(jobs.length*.55))throw new Error('Too few 2025 game detail pages archived');
