import fs from 'node:fs';

const SEASON=2026;
const DESERET_SEASON=SEASON+1; // fall 2026 is the 2026-27 school year
const MIN_GRAD_YEAR=SEASON+1;
const SOURCE='deseret-team-data-2026.json',OUT='deseret-rosters-stats-2026.json',MANUAL='manual-rosters-2026.json';
const BASE='https://sports.deseret.com';
const clean=v=>String(v??'').trim();
const slug=v=>clean(v).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
const compact=v=>clean(v).toUpperCase().replace(/[^A-Z0-9]/g,'');
const SLUG_OVERRIDES={ALA:'american-leadership',AMERICANLEADERSHIPACADEMY:'american-leadership',AMERICANLEADERSHIP:'american-leadership',CEDARCITY:'cedar',CEDAR:'cedar',GRANDCOUNTY:'grand',GRAND:'grand',GUNNISON:'gunnison-valley',GUNNISONVALLEY:'gunnison-valley',JUANDIEGOCATHOLIC:'juan-diego',JUANDIEGO:'juan-diego',LAYTONCHRISTIANACADEMY:'layton-christian',LAYTONCHRISTIAN:'layton-christian',MONUMENTVAL:'monument-valley',MONUMENTVALLEY:'monument-valley',MAPLEMTN:'maple-mountain',MAPLEMOUNTAIN:'maple-mountain',SAINTJOSEPH:'st-joseph',UMALEHI:'utah-military-camp-williams'};
const schoolSlug=v=>SLUG_OVERRIDES[compact(v)]||slug(v);
function decode(s){return String(s||'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16)))}
function htmlText(html){return decode(String(html||'')).replace(/<(script|style|noscript|svg)\b[^>]*>[\s\S]*?<\/\1>/gi,' ').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/(?:p|div|li|tr|h[1-6]|section|article)>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/[ \t]+/g,' ').replace(/\n\s+/g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
const cellText=html=>htmlText(html).replace(/\s+/g,' ').trim();
function tables(html){const out=[];const re=/<table\b[^>]*>([\s\S]*?)<\/table>/gi;let m;while((m=re.exec(html))){const rows=[];const rr=/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi;let rm;while((rm=rr.exec(m[1]))){const cells=[];const cr=/<(?:th|td)\b[^>]*>([\s\S]*?)<\/(?:th|td)>/gi;let cm;while((cm=cr.exec(rm[1])))cells.push(cellText(cm[1]));if(cells.some(Boolean))rows.push(cells)}if(rows.length)out.push({rows,context:htmlText(html.slice(Math.max(0,m.index-1600),m.index))})}return out}
function playerName(v){return clean(v).replace(/^\s*\.\s*/,'').replace(/^\s*[A-Z][A-Z'’-]*\s*\.\s*/i,'').replace(/\s+/g,' ').trim()}
function playerId(team,no,name){return `${slug(team)}-${slug(no||'x')}-${slug(name||'unknown')}`}
function findHeader(rows,predicate){return rows.findIndex(r=>predicate(r.map(x=>clean(x).toUpperCase().replace(/\s+/g,' '))))}
function gradYear(v){const m=clean(v).match(/20\d{2}/);return m?Number(m[0]):null}
function currentRosterPlayer(p){const y=gradYear(p?.class);return y===null||y>=MIN_GRAD_YEAR}
function parseRoster(html,team){for(const t of tables(html)){const hi=findHeader(t.rows,h=>h.includes('NO')&&h.some(x=>x.includes('PLAYER'))&&h.includes('CLASS')&&h.includes('POSITION'));if(hi<0)continue;const h=t.rows[hi].map(clean);const out=[];for(const row of t.rows.slice(hi+1)){if(!/^\d+[A-Z]?$/.test(clean(row[0])))continue;const vals=[...row];while(vals.length<h.length)vals.push('');const no=clean(vals[0]),name=playerName(vals[1]);if(!name)continue;const lookup=label=>{const i=h.findIndex(x=>clean(x).toUpperCase().includes(label));return i>=0?clean(vals[i]):''};const p={playerId:playerId(team,no,name),number:no,name,class:lookup('CLASS'),position:lookup('POSITION'),height:lookup('HEIGHT'),weight:lookup('WEIGHT')};if(currentRosterPlayer(p))out.push(p)}if(out.length)return out}return[]}
function category(headers,context=''){const h=headers.map(x=>clean(x).toUpperCase()),j=h.join('|'),c=clean(context).toUpperCase();if(j.includes('CARRIES')&&j.includes('YARD'))return'Rushing';if((j.includes('COMP-ATT')||j.includes('COMP - ATT'))&&j.includes('YARD'))return'Passing';if(j.includes('RECEPTIONS')&&j.includes('YARD'))return'Receiving';if(j.includes('FG')&&j.includes('PAT')&&!j.includes('TACKLES'))return'Kicking';if(j.includes('TACKLES')||j.includes('SACKS')||j.includes('PASS INT'))return'Defense/Special Teams';for(const x of ['RUSHING','PASSING','RECEIVING','KICKING','DEFENSE/SPECIAL TEAMS'])if(c.endsWith(x)||c.includes(`\n${x}`))return x.charAt(0)+x.slice(1).toLowerCase();return''}
function parseStats(html,team,roster){const byExact=new Map(roster.map(p=>[`${compact(p.number)}|${compact(p.name)}`,p])),out=[];const strict=roster.length>0;for(const t of tables(html)){const hi=findHeader(t.rows,h=>h.includes('NO')&&h.some(x=>x==='PLAYER'||x.includes('PLAYER')));if(hi<0)continue;const headers=t.rows[hi].map(clean),cat=category(headers,t.context);if(!cat)continue;const rows=[];for(const r of t.rows.slice(hi+1)){if(!/^\d+[A-Z]?$/.test(clean(r[0])))continue;const vals=[...r];while(vals.length<headers.length)vals.push('');const no=clean(vals[0]),rawName=playerName(vals[1]);if(!rawName)continue;const match=byExact.get(`${compact(no)}|${compact(rawName)}`);if(strict&&!match)continue;const name=match?.name||rawName,id=match?.playerId||playerId(team,no,name),values={};for(let i=2;i<headers.length;i++)values[headers[i]||`stat${i-1}`]=clean(vals[i]);rows.push({playerId:id,number:no,name,rosterMatched:!!match,values})}if(rows.length)out.push({category:cat,headers:headers.slice(2),rows})}return out}
async function fetchHtml(url){const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (compatible; RuralUtahSports/1.0; +https://ruralutahsports.github.io/)'},redirect:'follow',signal:AbortSignal.timeout(18000)});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.text()}
if(!fs.existsSync(SOURCE))throw new Error(`${SOURCE} missing`);const source=JSON.parse(fs.readFileSync(SOURCE,'utf8'));let prior={teams:{}};if(fs.existsSync(OUT)){try{prior=JSON.parse(fs.readFileSync(OUT,'utf8'))}catch{}}
let manual={};if(fs.existsSync(MANUAL)){try{manual=JSON.parse(fs.readFileSync(MANUAL,'utf8'))||{}}catch(e){console.warn(`manual roster file: ${e.message}`)}}
const manualFor=team=>{const key=Object.keys(manual).find(k=>compact(k)===compact(team));const rows=key&&Array.isArray(manual[key])?manual[key]:[];return rows.map(p=>({...p,playerId:playerId(team,p.number,p.name)})).filter(currentRosterPlayer)};
const entryMap=new Map(Object.values(source.teams||{}).map(x=>[compact(x.team),x]));
if(fs.existsSync('teams-data.json')){try{const siteTeams=JSON.parse(fs.readFileSync('teams-data.json','utf8'));for(const t of siteTeams||[]){const team=clean(t?.team);if(!team||entryMap.has(compact(team)))continue;const s=schoolSlug(team);entryMap.set(compact(team),{team,deseretSlug:s,rosterUrl:`${BASE}/high-school/school/${s}/football/roster/${DESERET_SEASON}`,statsUrl:`${BASE}/high-school/school/${s}/football/stats/${DESERET_SEASON}`})}}catch(e){console.warn(`teams-data fallback: ${e.message}`)}}
const entries=[...entryMap.values()],result={season:SEASON,deseretSeason:DESERET_SEASON,updatedAt:new Date().toISOString(),teams:{}};let next=0,rosterPages=0,statPages=0,rosterPlayers=0,statRows=0,failures=0,unversionedRosterFallbacks=0,unversionedStatsFallbacks=0,manualRosterTeams=0;
async function one(x){const team=x.team,s=schoolSlug(team);let roster=[],stats=[],rosterOk=false,statsOk=false;const versionedRoster=`${BASE}/high-school/school/${s}/football/roster/${DESERET_SEASON}`,versionedStats=`${BASE}/high-school/school/${s}/football/stats/${DESERET_SEASON}`;let rosterUrlUsed=versionedRoster,statsUrlUsed=versionedStats;
  try{let html=await fetchHtml(versionedRoster);roster=parseRoster(html,team);if(!roster.length){const fallback=`${BASE}/high-school/school/${s}/football/roster`;try{const fh=await fetchHtml(fallback),fr=parseRoster(fh,team);if(fr.length){roster=fr;rosterUrlUsed=fallback;unversionedRosterFallbacks++}}catch{}}rosterOk=true;rosterPages++;}catch(e){console.warn(`${team} roster: ${e.message}`)}
  const override=manualFor(team);if(override.length){roster=override;rosterOk=true;manualRosterTeams++}rosterPlayers+=roster.length;
  try{let html=await fetchHtml(versionedStats);stats=parseStats(html,team,roster);if(!stats.length){const fallback=`${BASE}/high-school/school/${s}/football/stats`;try{const fh=await fetchHtml(fallback),fs=parseStats(fh,team,roster);if(fs.length){stats=fs;statsUrlUsed=fallback;unversionedStatsFallbacks++}}catch{}}statsOk=true;statPages++;statRows+=stats.reduce((n,sec)=>n+sec.rows.length,0)}catch(e){console.warn(`${team} stats: ${e.message}`)}
  if(!rosterOk&&!statsOk){failures++;const old=prior.teams?.[team];if(old){result.teams[team]=old;return}}
  result.teams[team]={team,deseretSlug:x.deseretSlug||s,rosterUrl:rosterUrlUsed,statsUrl:statsUrlUsed,roster,stats,rosterFetched:rosterOk,statsFetched:statsOk,manualRoster:override.length>0}}
async function worker(){while(true){const i=next++;if(i>=entries.length)return;await one(entries[i]);await new Promise(r=>setTimeout(r,80))}}
await Promise.all(Array.from({length:Math.min(6,entries.length)},()=>worker()));
result.summary={teams:entries.length,rosterPages,statPages,teamsWithRoster:Object.values(result.teams).filter(x=>x.roster?.length).length,teamsWithStats:Object.values(result.teams).filter(x=>x.stats?.some(s=>s.rows?.length)).length,rosterPlayers,statRows,failedTeams:failures,unversionedRosterFallbacks,unversionedStatsFallbacks,manualRosterTeams};
fs.writeFileSync(OUT,JSON.stringify(result,null,2)+'\n');console.log(`Roster/stat build: ${result.summary.teamsWithRoster} teams with rosters (${rosterPlayers} players); ${result.summary.teamsWithStats} teams with stats (${statRows} stat rows); ${unversionedRosterFallbacks} roster fallback(s); ${unversionedStatsFallbacks} stats fallback(s); ${manualRosterTeams} manual roster override(s).`);if(rosterPages<Math.max(20,Math.floor(entries.length*.5)))throw new Error(`Too many roster page failures: ${rosterPages}/${entries.length}`);
