import fs from 'node:fs';

const BASE='https://sports.deseret.com';
const SEASON=2025;
const TEAM_OUT='deseret-team-data-2025.json';
const ROSTER_OUT='deseret-rosters-stats-2025.json';
const ALIGN='full-season-alignment-2025.json';
const CURRENT='teams-data.json';
const clean=v=>String(v??'').trim();
const compact=v=>clean(v).toUpperCase().replace(/[^A-Z0-9]/g,'');
const slugify=v=>clean(v).toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

const SLUG_OVERRIDES={
  ALA:'american-leadership',AMERICANLEADERSHIPACADEMY:'american-leadership',AMERICANLEADERSHIP:'american-leadership',
  CEDARCITY:'cedar',CEDAR:'cedar',GRANDCOUNTY:'grand',GRAND:'grand',GUNNISON:'gunnison-valley',GUNNISONVALLEY:'gunnison-valley',
  JUANDIEGOCATHOLIC:'juan-diego',JUANDIEGO:'juan-diego',LAYTONCHRISTIANACADEMY:'layton-christian',LAYTONCHRISTIAN:'layton-christian',
  MONUMENTVAL:'monument-valley',MONUMENTVALLEY:'monument-valley',MAPLEMTN:'maple-mountain',MAPLEMOUNTAIN:'maple-mountain',
  SAINTJOSEPH:'st-joseph',STJOSEPH:'st-joseph',UMALEHI:'utah-military-camp-williams',UMAHILLFIELD:'utah-military-hill-field'
};
const ALIASES={CEDAR:'CEDARCITY',GRANDCOUNTY:'GRAND',GUNNISON:'GUNNISONVALLEY',MONUMENTVAL:'MONUMENTVALLEY',MAPLEMTN:'MAPLEMOUNTAIN',AMERICANLEADERSHIP:'ALA',AMERICANLEADERSHIPACADEMY:'ALA'};
const canon=v=>ALIASES[compact(v)]||compact(v);
const schoolSlug=v=>SLUG_OVERRIDES[compact(v)]||slugify(v);
function decode(s){return String(s||'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16)))}
function htmlText(html){return decode(String(html||'')).replace(/<(script|style|noscript|svg)\b[^>]*>[\s\S]*?<\/\1>/gi,' ').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/(?:p|div|li|tr|h[1-6]|section|article)>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/[ \t]+/g,' ').replace(/\n\s+/g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
const cellText=html=>htmlText(html).replace(/\s+/g,' ').trim();
function tables(html){const out=[];const re=/<table\b[^>]*>([\s\S]*?)<\/table>/gi;let m;while((m=re.exec(html))){const rows=[];const rr=/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi;let rm;while((rm=rr.exec(m[1]))){const cells=[];const cr=/<(?:th|td)\b[^>]*>([\s\S]*?)<\/(?:th|td)>/gi;let cm;while((cm=cr.exec(rm[1])))cells.push(cellText(cm[1]));if(cells.some(Boolean))rows.push(cells)}if(rows.length)out.push({rows,context:htmlText(html.slice(Math.max(0,m.index-1800),m.index))})}return out}
function playerName(v){return clean(v).replace(/^\s*[A-Z][A-Z'’-]*\s*\.\s*/i,'').replace(/\s+/g,' ').trim()}
function playerId(team,no,name){return `${slugify(team)}-${slugify(no||'x')}-${slugify(name||'unknown')}`}
function findHeader(rows,predicate){return rows.findIndex(r=>predicate(r.map(x=>clean(x).toUpperCase().replace(/\s+/g,' '))))}
function parseRoster(html,team){for(const t of tables(html)){const hi=findHeader(t.rows,h=>h.includes('NO')&&h.some(x=>x.includes('PLAYER'))&&h.includes('CLASS')&&h.includes('POSITION'));if(hi<0)continue;const h=t.rows[hi].map(clean),out=[];for(const row of t.rows.slice(hi+1)){if(!/^\d+[A-Z]?(?:\/\d+[A-Z]?)?$/.test(clean(row[0])))continue;const vals=[...row];while(vals.length<h.length)vals.push('');const no=clean(vals[0]),name=playerName(vals[1]);if(!name)continue;const lookup=label=>{const i=h.findIndex(x=>clean(x).toUpperCase().includes(label));return i>=0?clean(vals[i]):''};out.push({playerId:playerId(team,no,name),number:no,name,class:lookup('CLASS'),position:lookup('POSITION'),height:lookup('HEIGHT'),weight:lookup('WEIGHT')})}if(out.length)return out}return[]}
function category(headers,context=''){const h=headers.map(x=>clean(x).toUpperCase()),j=h.join('|'),c=clean(context).toUpperCase();if(j.includes('CARRIES')&&j.includes('YARD'))return'Rushing';if((j.includes('COMP-ATT')||j.includes('COMP - ATT'))&&j.includes('YARD'))return'Passing';if(j.includes('RECEPTIONS')&&j.includes('YARD'))return'Receiving';if(j.includes('FG')&&j.includes('PAT')&&!j.includes('TACKLES'))return'Kicking';if(j.includes('TACKLES')||j.includes('SACKS')||j.includes('PASS INT')||j.includes('INTERCEPTIONS'))return'Defense/Special Teams';for(const x of ['RUSHING','PASSING','RECEIVING','KICKING','DEFENSE/SPECIAL TEAMS'])if(c.includes(x))return x==='DEFENSE/SPECIAL TEAMS'?x:x.charAt(0)+x.slice(1).toLowerCase();return''}
function parseStats(html,team,roster){const byNo=new Map(roster.map(p=>[compact(p.number),p])),out=[];for(const t of tables(html)){const hi=findHeader(t.rows,h=>h.includes('NO')&&h.some(x=>x==='PLAYER'||x.includes('PLAYER')));if(hi<0)continue;const headers=t.rows[hi].map(clean),cat=category(headers,t.context);if(!cat)continue;const rows=[];for(const r of t.rows.slice(hi+1)){if(!/^\d+[A-Z]?(?:\/\d+[A-Z]?)?$/.test(clean(r[0])))continue;const vals=[...r];while(vals.length<headers.length)vals.push('');const no=clean(vals[0]),rawName=playerName(vals[1]);if(!rawName)continue;const match=byNo.get(compact(no));const name=match?.name||rawName,id=match?.playerId||playerId(team,no,name),values={};for(let i=2;i<headers.length;i++)values[headers[i]||`stat${i-1}`]=clean(vals[i]);rows.push({playerId:id,number:no,name,rosterMatched:!!match,values})}if(rows.length)out.push({category:cat,headers:headers.slice(2),rows})}return out}
function extractGames(html,team){const text=String(html||'').replace(/\\u002F/gi,'/').replace(/\\\//g,'/'),out=new Map();const re=/(?:href=["']|["'])(https?:\/\/sports\.deseret\.com)?(\/high-school\/football\/game\/(\d{4}-\d{2}-\d{2})\/([^"'?#<>]+?)\/(\d+))(?:[?"'#<]|$)/gi;let m;while((m=re.exec(text))){if(!m[3].startsWith(`${SEASON}-`))continue;const mm=m[4].match(/^(.+?)-football-vs-(.+?)-football$/i);if(!mm)continue;const url=`${BASE}${m[2]}`;out.set(url,{date:m[3],awaySlug:mm[1],homeSlug:mm[2],gameId:m[5],url})}return [...out.values()]}
function humanize(s){return clean(s).replace(/-football$/i,'').split('-').filter(Boolean).map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(' ')}
async function fetchHtml(url){const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (compatible; RuralUtahSports/1.0; +https://ruralutahsports.github.io/)'},redirect:'follow',signal:AbortSignal.timeout(22000)});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.text()}

if(!fs.existsSync(ALIGN)||!fs.existsSync(CURRENT))throw new Error('2025 alignment or teams-data.json missing');
const alignment=JSON.parse(fs.readFileSync(ALIGN,'utf8')),current=JSON.parse(fs.readFileSync(CURRENT,'utf8')),meta=new Map(current.map(t=>[canon(t.team),t]));
const historical=[];for(const r of alignment.regions||[])for(const name of r.teams||[]){if(['ESCALANTE','USDB'].includes(compact(name)))continue;if(historical.some(x=>canon(x.team)===canon(name)))continue;const m=meta.get(canon(name))||{};historical.push({team:name,classification:r.classification,region:r.region,backgroundColor:m.backgroundColor||'#222222',textColor:m.textColor||'#FFFFFF',mascot:m.mascot||''})}
let priorTeam={teams:{}},priorRoster={teams:{}};try{priorTeam=JSON.parse(fs.readFileSync(TEAM_OUT,'utf8'))}catch{}try{priorRoster=JSON.parse(fs.readFileSync(ROSTER_OUT,'utf8'))}catch{}
const teamOut={season:SEASON,updatedAt:new Date().toISOString(),source:'Deseret 2025 archived football pages + RUS 2025 alignment',teams:{}},rosterOut={season:SEASON,updatedAt:new Date().toISOString(),source:'Deseret 2025 archived roster/stat pages',teams:{}};
let next=0,okSchedule=0,okRoster=0,okStats=0,failures=0,totalGames=0,totalPlayers=0,totalStatRows=0;
async function buildOne(t){const team=t.team,slug=schoolSlug(team),scheduleUrl=`${BASE}/high-school/school/${slug}/football/scores-schedule/${SEASON}`,rosterUrl=`${BASE}/high-school/school/${slug}/football/roster/${SEASON}`,statsUrl=`${BASE}/high-school/school/${slug}/football/stats/${SEASON}`;let games=[],roster=[],stats=[],scheduleOk=false,rosterOk=false,statsOk=false;try{const html=await fetchHtml(scheduleUrl);games=extractGames(html,team).map(g=>({date:g.date,awayTeam:humanize(g.awaySlug),homeTeam:humanize(g.homeSlug),gameUrl:g.url,gameId:g.gameId}));scheduleOk=true;okSchedule++;totalGames+=games.length}catch(e){console.warn(`${team} schedule: ${e.message}`)}try{const html=await fetchHtml(rosterUrl);roster=parseRoster(html,team);rosterOk=true;okRoster++;totalPlayers+=roster.length}catch(e){console.warn(`${team} roster: ${e.message}`)}try{const html=await fetchHtml(statsUrl);stats=parseStats(html,team,roster);statsOk=true;okStats++;totalStatRows+=stats.reduce((n,s)=>n+s.rows.length,0)}catch(e){console.warn(`${team} stats: ${e.message}`)}if(!scheduleOk&&!rosterOk&&!statsOk)failures++;const oldT=priorTeam.teams?.[team]||{},oldR=priorRoster.teams?.[team]||{};teamOut.teams[team]={team,classification:t.classification,region:t.region,backgroundColor:t.backgroundColor,textColor:t.textColor,mascot:t.mascot,deseretSlug:slug,scheduleUrl,rosterUrl,statsUrl,schedule:scheduleOk?games:(oldT.schedule||[]),scheduleFetched:scheduleOk};rosterOut.teams[team]={team,classification:t.classification,region:t.region,backgroundColor:t.backgroundColor,textColor:t.textColor,mascot:t.mascot,deseretSlug:slug,rosterUrl,statsUrl,roster:rosterOk?roster:(oldR.roster||[]),stats:statsOk?stats:(oldR.stats||[]),rosterFetched:rosterOk,statsFetched:statsOk};await sleep(80)}
async function worker(){while(true){const i=next++;if(i>=historical.length)return;await buildOne(historical[i])}}
await Promise.all(Array.from({length:Math.min(5,historical.length)},()=>worker()));
teamOut.summary={teams:historical.length,schedulePages:okSchedule,teamsWithGames:Object.values(teamOut.teams).filter(x=>x.schedule?.length).length,totalTeamScheduleEntries:totalGames,failedTeams:failures};
rosterOut.summary={teams:historical.length,rosterPages:okRoster,statPages:okStats,teamsWithRoster:Object.values(rosterOut.teams).filter(x=>x.roster?.length).length,teamsWithStats:Object.values(rosterOut.teams).filter(x=>x.stats?.some(s=>s.rows?.length)).length,rosterPlayers:totalPlayers,statRows:totalStatRows,failedTeams:failures};
fs.writeFileSync(TEAM_OUT,JSON.stringify(teamOut,null,2)+'\n');fs.writeFileSync(ROSTER_OUT,JSON.stringify(rosterOut,null,2)+'\n');
console.log('2025 team archive',teamOut.summary);console.log('2025 roster/stat archive',rosterOut.summary);
if(okRoster<Math.max(20,Math.floor(historical.length*.35)))throw new Error(`Too many 2025 roster failures: ${okRoster}/${historical.length}`);
