import fs from 'node:fs';
import {applyRosterStatCorrections} from './apply_manual_stat_corrections.mjs';

const FILE='deseret-rosters-stats-2026.json';
const BASE='https://sports.deseret.com';
const clean=v=>String(v??'').trim();
const compact=v=>clean(v).toUpperCase().replace(/[^A-Z0-9]/g,'');
function decode(s){return String(s||'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16)))}
function htmlText(html){return decode(String(html||'')).replace(/<(script|style|noscript|svg)\b[^>]*>[\s\S]*?<\/\1>/gi,' ').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/(?:p|div|li|tr|h[1-6]|section|article)>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/[ \t]+/g,' ').replace(/\n\s+/g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
const cellText=html=>htmlText(html).replace(/\s+/g,' ').trim();
function tables(html){const out=[];const re=/<table\b[^>]*>([\s\S]*?)<\/table>/gi;let m;while((m=re.exec(html))){const rows=[];const rr=/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi;let rm;while((rm=rr.exec(m[1]))){const cells=[];const cr=/<(?:th|td)\b[^>]*>([\s\S]*?)<\/(?:th|td)>/gi;let cm;while((cm=cr.exec(rm[1])))cells.push(cellText(cm[1]));if(cells.some(Boolean))rows.push(cells)}if(rows.length)out.push({rows,context:htmlText(html.slice(Math.max(0,m.index-1600),m.index))})}return out}
function playerName(v){return clean(v).replace(/^\s*\.\s*/,'').replace(/^\s*[A-Z][A-Z'’-]*\s*\.\s*/i,'').replace(/\s+/g,' ').trim()}
function findHeader(rows,predicate){return rows.findIndex(r=>predicate(r.map(x=>clean(x).toUpperCase().replace(/\s+/g,' '))))}
function category(headers,context=''){const h=headers.map(x=>clean(x).toUpperCase()),j=h.join('|'),c=clean(context).toUpperCase();if(j.includes('CARRIES')&&j.includes('YARD'))return'Rushing';if((j.includes('COMP-ATT')||j.includes('COMP - ATT'))&&j.includes('YARD'))return'Passing';if(j.includes('RECEPTIONS')&&j.includes('YARD'))return'Receiving';if(j.includes('FG')&&j.includes('PAT')&&!j.includes('TACKLES'))return'Kicking';if(j.includes('TACKLES')||j.includes('SACKS')||j.includes('PASS INT'))return'Defense/Special Teams';for(const x of ['RUSHING','PASSING','RECEIVING','KICKING','DEFENSE/SPECIAL TEAMS'])if(c.endsWith(x)||c.includes(`\n${x}`))return x.charAt(0)+x.slice(1).toLowerCase();return''}
function parseStats(html,roster){const byExact=new Map((roster||[]).map(p=>[`${compact(p.number)}|${compact(p.name)}`,p])),out=[];const strict=byExact.size>0;for(const t of tables(html)){const hi=findHeader(t.rows,h=>h.includes('NO')&&h.some(x=>x==='PLAYER'||x.includes('PLAYER')));if(hi<0)continue;const headers=t.rows[hi].map(clean),cat=category(headers,t.context);if(!cat)continue;const rows=[];for(const r of t.rows.slice(hi+1)){if(!/^\d+[A-Z]?$/.test(clean(r[0])))continue;const vals=[...r];while(vals.length<headers.length)vals.push('');const no=clean(vals[0]),rawName=playerName(vals[1]);if(!rawName)continue;const match=byExact.get(`${compact(no)}|${compact(rawName)}`);if(strict&&!match)continue;const values={};for(let i=2;i<headers.length;i++)values[headers[i]||`stat${i-1}`]=clean(vals[i]);rows.push({playerId:match?.playerId||'',number:no,name:match?.name||rawName,rosterMatched:!!match,values})}if(rows.length)out.push({category:cat,headers:headers.slice(2),rows})}return out}
async function fetchHtml(url){const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (compatible; RuralUtahSports/1.0; +https://ruralutahsports.github.io/)'},redirect:'follow',signal:AbortSignal.timeout(18000)});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.text()}
const nonEmpty=v=>v!==null&&v!==undefined&&clean(v)!=='';
function numeric(v){const s=clean(v).replace(/,/g,'').replace(/%$/,'');if(!/^-?\d+(?:\.\d+)?$/.test(s))return null;const n=Number(s);return Number.isFinite(n)?n:null}
function composite(v){const m=clean(v).match(/^\s*(-?\d+(?:\.\d+)?)\s*[-/]\s*(-?\d+(?:\.\d+)?)\s*$/);return m?[Number(m[1]),Number(m[2])]:null}
function volatileHeader(h){return /AVG|AVERAGE|PCT|PERCENT|RATE|LONG|LNG/.test(compact(h))}
function rowCompleteness(row){return Object.values(row?.values||{}).filter(nonEmpty).length}
function endpointScore(stats){let sections=0,rows=0,cells=0;for(const sec of stats||[]){if(!sec.rows?.length)continue;sections++;rows+=sec.rows.length;for(const row of sec.rows)cells+=rowCompleteness(row)}return{sections,rows,cells}}
function betterEndpoint(a,b){const sa=a?.score||{sections:0,rows:0,cells:0},sb=b?.score||{sections:0,rows:0,cells:0};if(sa.cells!==sb.cells)return sa.cells>sb.cells?a:b;if(sa.rows!==sb.rows)return sa.rows>sb.rows?a:b;if(sa.sections!==sb.sections)return sa.sections>sb.sections?a:b;return a?.kind==='live'?a:b}
function mergeValue(header,a,b,preferred){if(!nonEmpty(a))return b;if(!nonEmpty(b))return a;if(clean(a)===clean(b))return a;const ca=composite(a),cb=composite(b);if(ca&&cb&&!volatileHeader(header)){if(ca[1]!==cb[1])return ca[1]>cb[1]?a:b;if(ca[0]!==cb[0])return ca[0]>cb[0]?a:b}const na=numeric(a),nb=numeric(b);if(na!==null&&nb!==null&&!volatileHeader(header)&&na>=0&&nb>=0)return na>=nb?a:b;return preferred==='b'?b:a}
function rowKey(row){return clean(row?.playerId)||`${compact(row?.number)}|${compact(row?.name)}`}
function mergeSections(aStats,bStats,preferredKind){const categories=[];for(const s of [...(aStats||[]),...(bStats||[])])if(s?.category&&!categories.includes(s.category))categories.push(s.category);const merged=[];for(const cat of categories){const aSecs=(aStats||[]).filter(s=>s.category===cat),bSecs=(bStats||[]).filter(s=>s.category===cat);const headers=[];for(const sec of [...aSecs,...bSecs])for(const h of sec.headers||Object.keys(sec.rows?.[0]?.values||{}))if(h&&!headers.some(x=>compact(x)===compact(h)))headers.push(h);const aRows=new Map(),bRows=new Map();for(const sec of aSecs)for(const row of sec.rows||[])aRows.set(rowKey(row),row);for(const sec of bSecs)for(const row of sec.rows||[])bRows.set(rowKey(row),row);const valueHeaders=[...headers];for(const row of [...aRows.values(),...bRows.values()])for(const h of Object.keys(row?.values||{}))if(h&&!valueHeaders.some(x=>compact(x)===compact(h)))valueHeaders.push(h);const keys=[...new Set([...aRows.keys(),...bRows.keys()])],rows=[];for(const key of keys){const a=aRows.get(key),b=bRows.get(key),preferred=preferredKind==='live'?'b':'a',base=(preferred==='b'?b:a)||a||b;if(!base)continue;const values={};for(const h of valueHeaders){const ah=Object.keys(a?.values||{}).find(x=>compact(x)===compact(h)),bh=Object.keys(b?.values||{}).find(x=>compact(x)===compact(h));const v=mergeValue(h,ah?a.values[ah]:undefined,bh?b.values[bh]:undefined,preferred);if(nonEmpty(v))values[h]=v}rows.push({...base,playerId:base.playerId||a?.playerId||b?.playerId||'',number:base.number||a?.number||b?.number||'',name:base.name||a?.name||b?.name||'',rosterMatched:!!(a?.rosterMatched||b?.rosterMatched),values})}if(rows.length)merged.push({category:cat,headers:valueHeaders.filter(h=>rows.some(r=>nonEmpty(r.values?.[h]))),rows})}return merged}

if(!fs.existsSync(FILE))throw new Error(`${FILE} missing`);
const data=JSON.parse(fs.readFileSync(FILE,'utf8'));
const season=Number(data.deseretSeason||Number(data.season||2026)+1);
let checked=0,bothSucceeded=0,oneSucceeded=0,bothNonEmpty=0,mergedTeams=0,endpointFailures=0,next=0;
const entries=Object.entries(data.teams||{});
async function one([teamKey,team]){const slug=clean(team.deseretSlug);if(!slug)return;const versioned=`${BASE}/high-school/school/${slug}/football/stats/${season}`,live=`${BASE}/high-school/school/${slug}/football/stats`;const endpoints=[{kind:'versioned',url:versioned},{kind:'live',url:live}];const results=[];for(const ep of endpoints){try{const html=await fetchHtml(ep.url),stats=parseStats(html,team.roster||[]);results.push({...ep,ok:true,stats,score:endpointScore(stats)})}catch(e){endpointFailures++;console.warn(`${teamKey} ${ep.kind} stats: ${e.message}`);results.push({...ep,ok:false,stats:[],score:{sections:0,rows:0,cells:0}})}}checked++;const ok=results.filter(x=>x.ok);if(ok.length===2)bothSucceeded++;else if(ok.length===1)oneSucceeded++;const withStats=results.filter(x=>x.score.rows>0);if(withStats.length===2)bothNonEmpty++;if(!withStats.length){team.statsEndpointsChecked=endpoints.map(x=>x.url);team.statsEndpointMerge={versioned:results[0].score,live:results[1].score,preferred:'existing',bothFetched:ok.length===2};return}const preferred=betterEndpoint(results[0],results[1]);let stats;if(withStats.length===2){stats=mergeSections(results[0].stats,results[1].stats,preferred?.kind||'live');mergedTeams++}else stats=withStats[0].stats;team.stats=stats;team.statsFetched=true;team.statsUrl=preferred?.url||withStats[0].url;team.statsEndpointsChecked=endpoints.map(x=>x.url);team.statsEndpointMerge={versioned:results[0].score,live:results[1].score,preferred:preferred?.kind||withStats[0].kind,bothFetched:ok.length===2}}
async function worker(){while(true){const i=next++;if(i>=entries.length)return;await one(entries[i]);await new Promise(r=>setTimeout(r,80))}}
await Promise.all(Array.from({length:Math.min(6,entries.length)},()=>worker()));
applyRosterStatCorrections(data);
data.updatedAt=new Date().toISOString();
const statRows=Object.values(data.teams||{}).reduce((total,team)=>total+(team.stats||[]).reduce((sum,section)=>sum+(section.rows||[]).length,0),0);
data.summary={...(data.summary||{}),statRows,statsEndpointMerge:{checked,bothSucceeded,oneSucceeded,bothNonEmpty,mergedTeams,endpointFailures}};
fs.writeFileSync(FILE,JSON.stringify(data,null,2)+'\n');
console.log(`Deseret stats endpoint merge: checked ${checked} teams; both endpoints succeeded for ${bothSucceeded}; both had stats for ${bothNonEmpty}; merged ${mergedTeams}; endpoint failures ${endpointFailures}.`);
if(checked<Math.max(20,Math.floor(entries.length*.5)))throw new Error(`Too few teams checked across both stats endpoints: ${checked}/${entries.length}`);
